CREATE TABLE IF NOT EXISTS ca_streams(tenant_id TEXT NOT NULL,object_key TEXT NOT NULL,kind TEXT NOT NULL,actor TEXT NOT NULL DEFAULT '',metadata TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,next_seq INTEGER NOT NULL DEFAULT 1,next_id INTEGER NOT NULL DEFAULT 2,state TEXT NOT NULL DEFAULT 'importing',bootstrap_hash TEXT,PRIMARY KEY(tenant_id,object_key));
CREATE INDEX IF NOT EXISTS ca_streams_browse ON ca_streams(tenant_id,kind,updated_at DESC,object_key);
CREATE TABLE IF NOT EXISTS ca_commits(tenant_id TEXT NOT NULL,object_key TEXT NOT NULL,seq INTEGER NOT NULL,payload TEXT NOT NULL,checksum TEXT NOT NULL,bytes INTEGER NOT NULL,next_id INTEGER NOT NULL,PRIMARY KEY(tenant_id,object_key,seq));
CREATE TABLE IF NOT EXISTS ca_sessions(tenant_id TEXT NOT NULL,object_key TEXT NOT NULL,session_id INTEGER NOT NULL,record TEXT NOT NULL,name TEXT NOT NULL DEFAULT '',PRIMARY KEY(tenant_id,object_key,session_id));
CREATE TABLE IF NOT EXISTS ca_entries(tenant_id TEXT NOT NULL,object_key TEXT NOT NULL,entry_id INTEGER NOT NULL,session_id INTEGER NOT NULL,commit_seq INTEGER NOT NULL,entry TEXT NOT NULL,PRIMARY KEY(tenant_id,object_key,entry_id));
CREATE INDEX IF NOT EXISTS ca_entries_session ON ca_entries(tenant_id,object_key,session_id,entry_id DESC);
CREATE TABLE IF NOT EXISTS ca_bootstrap(tenant_id TEXT NOT NULL,object_key TEXT NOT NULL,ordinal INTEGER NOT NULL,payload TEXT NOT NULL,checksum TEXT NOT NULL,PRIMARY KEY(tenant_id,object_key,ordinal));
CREATE TABLE IF NOT EXISTS ca_channel_messages(tenant_id TEXT NOT NULL,object_key TEXT NOT NULL,message_id TEXT NOT NULL,operation_id TEXT NOT NULL,event TEXT NOT NULL,receipt TEXT,native_seq INTEGER NOT NULL DEFAULT 0,observed_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,object_key,message_id),UNIQUE(tenant_id,object_key,operation_id));
CREATE TABLE IF NOT EXISTS ca_asks(tenant_id TEXT NOT NULL,object_key TEXT NOT NULL,operation_id TEXT NOT NULL,request_hash TEXT NOT NULL,prompt TEXT NOT NULL,PRIMARY KEY(tenant_id,object_key,operation_id));
