export const githubPanel = `<section><h2>GitHub 파일 작성</h2><p>관리자 개인의 초안과 대화를 별도로 저장합니다. 기존 브랜치의 지정 폴더에서 Markdown·텍스트·JSON·YAML·JavaScript·TypeScript·CSS·TOML을 작성할 수 있습니다. 저장한 파일은 스킬로 자동 활성화되지 않습니다.</p><button type="button" id="github-refresh">연결 확인 / 저장소 조회</button><pre id="github-status"></pre><form id="github-source"><label>저장소 <select name="repositoryId" required></select></label><button type="button" id="github-next" disabled>다음 저장소</button><label>기존 브랜치 <input name="branch" required maxlength="200" placeholder="main"></label><label>작성 폴더 <input name="prefix" required maxlength="240" placeholder="skills/personal/" pattern=".+/"></label><label>사용할 구독 계정 <select name="accountId" required></select></label><button>이 위치에 초안 만들기</button></form><label>내 작성 위치 <select id="github-sources"><option value="">위치를 선택하세요</option></select></label><div id="github-editor" hidden><p id="github-destination"></p><button type="button" id="github-files">파일 목록</button><div id="github-file-list"></div><form id="github-stage"><label>폴더 안의 파일 경로 <input name="path" required maxlength="240" placeholder="greeting/SKILL.md"></label><label>파일 내용 <textarea name="content" rows="16" spellcheck="false" required></textarea></label><button>초안에 담기</button></form><form id="github-ask"><label>AI에게 작성 요청 <textarea name="prompt" required maxlength="8000" rows="3"></textarea></label><button>AI 초안 작성</button></form><pre id="github-answer"></pre><form id="github-preview"><label>커밋 설명 <input name="message" required maxlength="200" placeholder="Add greeting skill"></label><button>저장할 내용 확인</button></form><pre id="github-plan"></pre><button type="button" id="github-publish" disabled>확인한 내용 Git에 저장</button><pre id="github-receipts"></pre><details><summary>내 작성 대화</summary><pre id="github-history"></pre></details><button type="button" id="github-disable">이 작성 위치 비활성화</button></div></section>`;

export const githubScript = `
let githubSource='',githubVersion=0,githubPlan=null,githubNext=null;
const githubPending=new Map();
function githubInvalidate(){githubPlan=null;$('github-plan').textContent='';$('github-publish').disabled=true;}
async function githubLoad(page=1){const [status,inventory,overview]=await Promise.all([api('/api/github/status'),api('/api/github/repositories?page='+page),api('/api/overview')]);$('github-status').textContent=JSON.stringify(status,null,2);if(page===1)$('github-source').elements.repositoryId.innerHTML='';$('github-source').elements.repositoryId.innerHTML+=inventory.repositories.map(r=>'<option value="'+esc(r.id)+'" data-branch="'+esc(r.defaultBranch)+'">'+esc(r.name)+(r.private?' · 비공개':' · 공개')+'</option>').join('');githubNext=inventory.nextPage;$('github-next').disabled=!githubNext;$('github-source').elements.accountId.innerHTML=overview.accounts.filter(a=>a.connected&&a.directUsageGranted).map(a=>'<option value="'+esc(a.id)+'">'+esc(a.label)+'</option>').join('');$('github-sources').innerHTML='<option value="">위치를 선택하세요</option>'+status.sources.filter(s=>s.enabled).map(s=>'<option value="'+esc(s.id)+'">'+esc(s.repository+' · '+s.branch+' · '+s.prefix)+'</option>').join('');$('github-sources').value=githubSource;const option=$('github-source').elements.repositoryId.selectedOptions[0];if(option)$('github-source').elements.branch.value=option.dataset.branch;}
async function githubState(){if(!githubSource)return;const chosen=githubSource;const state=await api('/api/github/draft?sourceId='+encodeURIComponent(chosen));if(chosen!==githubSource)return;githubVersion=state.version;$('github-destination').textContent=state.repository+' · '+state.branch+' · '+state.prefix+' · 초안 버전 '+state.version+' · 계정 '+state.accountId;$('github-receipts').textContent=JSON.stringify(state.publications,null,2);$('github-history').textContent=JSON.stringify({displayLimits:state.displayLimits,entries:state.entries},null,2);$('github-editor').hidden=false;}
$('github-refresh').onclick=()=>run(()=>githubLoad());$('github-next').onclick=()=>run(()=>githubLoad(githubNext));
$('github-source').elements.repositoryId.onchange=e=>{const option=e.target.selectedOptions[0];if(option)$('github-source').elements.branch.value=option.dataset.branch;};
$('github-source').onsubmit=e=>{e.preventDefault();run(async()=>{const input=Object.fromEntries(new FormData(e.target));input.repositoryId=Number(input.repositoryId);const source=await api('/api/github/source',input);githubSource=source.id;githubInvalidate();await githubLoad();await githubState();});};
$('github-sources').onchange=e=>run(async()=>{githubSource=e.target.value;githubInvalidate();$('github-editor').hidden=!githubSource;$('github-file-list').innerHTML='';$('github-stage').reset();$('github-answer').textContent='';if(githubSource)await githubState();});
$('github-files').onclick=()=>run(async()=>{const chosen=githubSource,data=await api('/api/github/files?sourceId='+encodeURIComponent(chosen));if(chosen!==githubSource)return;$('github-file-list').innerHTML=data.files.map(f=>'<p><button type="button" data-github-file="'+esc(f.path)+'" '+(f.editable?'':'disabled')+'>'+esc(f.path)+'</button>'+(f.staged?' · 초안':f.editable?'':' · 편집할 수 없는 파일')+'</p>').join('')||'<p>이 폴더에는 파일이 없습니다. 새 파일 경로를 입력하세요.</p>';});
$('github-file-list').onclick=e=>{const button=e.target.closest('button[data-github-file]');if(!button)return;run(async()=>{const chosen=githubSource,data=await api('/api/github/file?'+new URLSearchParams({sourceId:chosen,path:button.dataset.githubFile}));if(chosen!==githubSource)return;$('github-stage').elements.path.value=data.path;$('github-stage').elements.content.value=data.content;});};
$('github-stage').onsubmit=e=>{e.preventDefault();run(async()=>{const input={...Object.fromEntries(new FormData(e.target)),sourceId:githubSource,expectedVersion:githubVersion,operationId:'stage-'+crypto.randomUUID()};await api('/api/github/stage',input);githubInvalidate();await githubState();});};
$('github-ask').onsubmit=e=>{e.preventDefault();run(async()=>{const chosen=githubSource,input={sourceId:chosen,prompt:new FormData(e.target).get('prompt'),operationId:'ask-'+crypto.randomUUID()},result=await api('/api/github/ask',input);if(chosen!==githubSource)return;$('github-answer').textContent=result.text;githubInvalidate();await githubState();});};
$('github-preview').onsubmit=e=>{e.preventDefault();run(async()=>{const chosen=githubSource,plan=await api('/api/github/preview',{sourceId:chosen,message:new FormData(e.target).get('message')});if(chosen!==githubSource)return;githubPlan=plan;$('github-plan').textContent=JSON.stringify(plan,null,2);$('github-publish').disabled=false;});};
$('github-publish').onclick=()=>run(async()=>{if(!githubPlan)throw Error('먼저 저장할 내용을 확인하세요');const chosen=githubSource,plan=githubPlan,key=chosen+':'+plan.planHash;let input=githubPending.get(key);if(!input){input={sourceId:chosen,planHash:plan.planHash,operationId:'publish-'+crypto.randomUUID()};githubPending.set(key,input);}const result=await api('/api/github/publish',input);if(chosen!==githubSource)return;if(result.state==='completed'){githubPending.delete(key);githubInvalidate();}$('github-receipts').textContent=JSON.stringify(result,null,2);await githubState();if(result.state==='unknown')throw Error('저장 결과가 불확실합니다. GitHub 브랜치를 확인해야 하며 자동 재시도하지 않습니다.');});
$('github-disable').onclick=()=>run(async()=>{if(!confirm('이 작성 위치를 비활성화할까요? 기존 초안은 더 이상 사용할 수 없습니다.'))return;await api('/api/github/disable',{sourceId:githubSource});githubSource='';githubInvalidate();$('github-editor').hidden=true;await githubLoad();});
`;
