import assert from "node:assert/strict";
import { createHash, createHmac, randomBytes, randomUUID } from "node:crypto";
import { mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Miniflare, convertV4MiniflareOptions } from "miniflare";
import { piTextModules } from "./pi-modules.mjs";
import { workflowDefinition, workflowFromSkill, workflowFinalText, workflowInput, workflowRender, workflowSource } from "../../workers/pi/workflow.js";
process.chdir(fileURLToPath(new URL("../..", import.meta.url)));
const channel="fixture-channel",group="fixture-group",root="fixture-root",manager="fixture-manager",origin="https://events.example.invalid",signing="ab".repeat(32),token="fixture-visit-token-at-least-32-characters";
const patientId="10000000-0000-0000-0000-000000000001",visitId="20000000-0000-0000-0000-000000000001",reservationId="30000000-0000-0000-0000-000000000001",otherReservation="30000000-0000-0000-0000-000000000002";
const performed={procedureText:"  Synthetic procedure A (2025-12-25)\nSynthetic procedure A (2025-12-29)  ",pod:"Synthetic procedure A (2025-12-25): POD 7\nSynthetic procedure A (2025-12-29): POD 3"};
const hash=value=>createHash("sha256").update(value).digest("hex"),persistence=await mkdtemp(join(tmpdir(),"workflow-check-")),wrapping=randomBytes(32).toString("base64url");
const definitions={};const bundles={};for(const name of ["visit-handoff","staff-notice"]){const rawContent=await readFile(`skills/workflows/${name}/SKILL.md`,"utf8"),content=await readFile(`skills/workflows/${name}/references/workflow.json`,"utf8");const definition=JSON.parse(content);if(name==="visit-handoff"){definition.fields.find(field=>field.id==="area").source="intake.concernText";definition.fields.push({id:"pod",label:"POD",type:"text",required:false,maxLength:40,source:"reservation.pod"},{id:"performed_procedure",label:"Performed procedures",type:"text",required:false,maxLength:1000,source:"performed.procedureText"},{id:"performed_pod",label:"Performed POD",type:"text",required:false,maxLength:1000,source:"performed.pod"});definition.template+="\nPOD: {{pod}}\nPerformed: {{performed_procedure}}\nPerformed POD: {{performed_pod}}";}definitions[name]=workflowDefinition(definition);bundles[name]={rawContent,resources:[{path:"references/workflow.json",kind:"reference",content:JSON.stringify(definition)}]};}
for(const mutate of [d=>({...d,schemaVersion:2}),d=>({...d,tenant:"untrusted"}),d=>({...d,template:"{{person.toUpperCase()}}"}),d=>({...d,template:"https://untrusted.invalid"}),d=>({...d,fields:[{...d.fields[0],source:"reservation.sql"}]}),d=>({...d,fields:Array(21).fill(d.fields[0])}),d=>({...d,confirmations:Array(11).fill(d.confirmations[0])})])assert.throws(()=>workflowDefinition(mutate(definitions["visit-handoff"])),/workflow_definition_invalid/);
assert.equal(workflowDefinition({schemaVersion:1,title:"Fixture fixed notice",source:"none",fields:[],template:"Fixture notice",confirmations:[]}).fields.length,0);
assert.throws(()=>workflowFromSkill({resources:[{path:"references/workflow.json",content:"{"}]}),/workflow_definition_invalid/);
const exactText="  Staff-authored heading\nFull replacement\twith spaces  ";
for(const text of [exactText,"x".repeat(4000),"한".repeat(4000),"😀".repeat(2000)])assert.equal(workflowFinalText(text),text);
for(const text of [""," \t\n",null,42,"x".repeat(4001),"😀".repeat(2001),"text\rnew",...Array.from({length:32},(_,i)=>"text"+String.fromCharCode(i)).filter(value=>!/[\t\n]$/.test(value)),"text\x7f","text\x85"])assert.throws(()=>workflowFinalText(text),/workflow_final_text_invalid/);
const pureInput={action:"prepare",name:"staff-notice",revision:"a".repeat(64),values:{audience:"운영팀",notice:"Synthetic notice",when:"Tomorrow"},finalText:exactText};
assert.equal(workflowInput(pureInput).finalText,exactText);assert.equal(workflowRender(definitions["staff-notice"],pureInput.values,null,exactText).text,exactText);assert.throws(()=>workflowRender(definitions["staff-notice"],{...pureInput.values,notice:""},null,exactText),/workflow_values_invalid/);assert.throws(()=>workflowInput({...pureInput,finalText:" \n"}),/workflow_final_text_invalid/);
for (const selection of [{patientId},{patientId,visitId:null},{visitId:null,patientId}]) assert.deepEqual(workflowInput({...pureInput,selection}).selection,{patientId,visitId:null},"Omitted and null schedules have the same canonical review selection");
for (const selection of [{visitId:null},{patientId,visitId:""},{patientId,visitId:false},{patientId,visitId:"bad"}]) assert.throws(()=>workflowInput({...pureInput,selection}),/workflow_input_invalid/);
assert.deepEqual(workflowSource({patient:{id:patientId,label:"Synthetic",reference:null},visits:[{id:visitId,reservationId}],reservations:[{id:reservationId,note:"UNSELECTED"}],selectedVisitId:null,intake:{concernText:"Synthetic patient concern"}}),{patient:{id:patientId,label:"Synthetic",reference:null},visit:null,reservation:null,intake:{concernText:"Synthetic patient concern"},performed:{procedureText:null,pod:null}});
assert.deepEqual(workflowSource({patient:{id:patientId,label:"Synthetic",reference:null},visits:[],reservations:[],selectedVisitId:null,performed:{...performed,hidden:"DO_NOT_PROJECT"}}).performed,performed,"Source normalization preserves exact performed strings and drops unknown properties");
await writeFile("build/pi/workflow-wrapper.js",`import worker,{Assistant as BaseAssistant,Credentials as BaseCredentials} from './index.js';export default worker;
export class Assistant extends BaseAssistant{async fetch(request){const path=new URL(request.url).pathname;if(path==='/fixture/inspect')return Response.json({rows:[...await this.ctx.storage.list({prefix:'workflow-delivery:'})].map(([key,value])=>({key,...value})),commandRows:this.channelSql.exec('SELECT COUNT(*) AS n FROM command_operations').toArray()[0].n,channelRows:this.channelSql.exec('SELECT COUNT(*) AS n FROM channel_messages').toArray()[0].n,runtime:this.channelSql.exec('SELECT data FROM channel_runtime').toArray(),modelCalls:this.faux.state.callCount});if(path==='/fixture/status'){const input=await request.json();try{return Response.json(await this.workflowStatus(input.target,input.operationId,input.requestDigest));}catch(error){return Response.json({error:error.message});}}if(path==='/fixture/stage'){const input=await request.json();await this.ctx.storage.put('workflow-delivery:'+input.operationId,{requestDigest:input.requestDigest,state:'sending'});return Response.json({ok:true});}if(path==='/fixture/send'){try{return Response.json(await this.workflowSend(await request.json()));}catch(error){return Response.json({error:error.message});}}return new Response(null,{status:404});}}
export class Credentials extends BaseCredentials{async adminSession(){return {principal:{email:'fixture-admin@example.invalid',role:'super_admin'},csrf:'fixture-csrf'};}async channelAccess(){return 'fixture-native-access';}async fetch(request){if(new URL(request.url).pathname==='/fixture/inspect')return Response.json({starts:[...await this.ctx.storage.list({prefix:'command-start:'})].map(([,row])=>row),preferences:[...await this.ctx.storage.list({prefix:'threadStart:'})].map(([,row])=>row),threads:await this.threads(),cursor:await this.ctx.storage.get('accountCursor')??0});if(new URL(request.url).pathname==='/fixture/start'){try{return Response.json(await this.commandStart(await request.json()));}catch(error){return Response.json({error:error.message});}}if(new URL(request.url).pathname==='/fixture/admin'){const input=await request.json();try{return Response.json(await this.adminMutation(input.action,input.input,'fixture-session','fixture-csrf'));}catch(error){return Response.json({error:error.message},{status:400});}}return new Response(null,{status:404});}}
`);
let noVisits=false,rootless=false,changed=false,relinked=false,denied=false,candidatesMissing=false,concernChanged=false,podChanged=false,performedProcedureChanged=false,performedPodChanged=false,writeMode="sent",observed=0;const reads=[],writes=[];
const options=(tenant="fixture-tenant")=>convertV4MiniflareOptions({resourcePersistencePath:persistence,workers:[
{name:"events",modulesRoot:resolve("build/events"),modules:[{type:"ESModule",path:resolve("build/events/index.js")}],compatibilityDate:"2026-10-01",compatibilityFlags:["nodejs_compat","global_fetch_strictly_public"],kvNamespaces:["OAUTH_KV"],durableObjects:{EVENTS:{className:"ChannelEvents",useSQLite:true},THREADS:{className:"ThreadHistory",useSQLite:true},...(rootless?{}:{PI_ASSISTANT:{className:"Assistant",scriptName:"cloud",useSQLite:true}}),PI_CREDENTIALS:{className:"Credentials",scriptName:"cloud",useSQLite:true}},serviceBindings:{VISIT_API:"visit"},bindings:{PUBLIC_ORIGIN:origin,EVENTS_OBJECT_NAME:"fixture-events",OAUTH_OWNER_ID:"fixture-owner",CHANNEL_SLUG:"fixture-channel",CHANNEL_APP_SIGNING_KEY:signing,ALLOWED_CHANNEL_ID:channel,ALLOWED_CHAT_ID:group,CHANNEL_APP_ID:"fixture-app",COMMAND_GROUP_IDS:JSON.stringify([group]),COMMAND_PRIVATE_MANAGERS:"{}",VISIT_SERVICE_TOKEN:token},outboundService:()=>assert.fail("Events has no arbitrary outbound workflow calls")},
{name:"cloud",modulesRoot:resolve("build/pi"),modules:[...["workflow-wrapper.js","index.js"].map(name=>({type:"ESModule",path:resolve("build/pi",name)})),...awaitModules],compatibilityDate:"2026-10-04",compatibilityFlags:["nodejs_compat","global_fetch_strictly_public"],d1Databases:["CONVERSATIONS"],durableObjects:{Assistant:{className:"Assistant",useSQLite:true},Credentials:{className:"Credentials",useSQLite:true}},bindings:{TENANT_ID:tenant,TOKEN_WRAPPING_KEY:wrapping,TOKEN_WRAPPING_AAD:"fixture/v1",PROBE_MODE:"mock",OPENAI_MODEL:"gpt-6.1-sol",ALLOWED_CHANNEL_ID:channel,ALLOWED_CHAT_ID:group,CHANNEL_APP_ID:"fixture-app",COMMAND_GROUP_IDS:JSON.stringify([group]),COMMAND_PRIVATE_MANAGERS:"{}",VISIT_MCP_GROUP_ID:group,CHANNEL_REPLY_ENABLED:"true",PUBLIC_ORIGIN:"https://cloud.example.invalid"},outboundService:async request=>{assert.equal(request.url,"https://app-store-api.channel.io/general/v1/native/functions");assert.equal(request.method,"PUT");assert.equal(request.headers.get("x-access-token"),"fixture-native-access");const body=await request.json();assert.equal(body.method,"writeGroupMessage");assert.equal(body.params.channelId,channel);assert.equal(body.params.groupId,group);assert.equal(body.params.rootMessageId,rootless?undefined:root);assert.equal(body.params.broadcast,false);assert.match(body.params.dto.requestId,rootless?/^start-[a-f0-9-]{36}$/:/^wfl-[a-f0-9-]{36}$/);assert.ok(!body.params.dto.files);writes.push(body.params);if(writeMode==="unknown")throw Error("fixture_lost_native_response");if(writeMode==="server-error")return Response.json({error:{message:"fixture_backend_error"}},{status:500});return Response.json({result:{message:{id:"fixture-reply-"+writes.length,...(writeMode==="cross-group"?{chatId:"wrong-group"}:writeMode==="thread"?{threadMsg:true,rootMessageId:root}:rootless?{channelId:channel,chatId:group,chatType:"group",threadMsg:false,rootMessageId:null}:{})}}});}},
{name:"visit",modulesRoot:resolve("build/visit"),modules:[{type:"ESModule",path:resolve("build/visit/index.js")}],compatibilityDate:"2026-10-01",bindings:{TENANT_ID:tenant,VISIT_SERVICE_TOKEN:token,SUPABASE_URL:"https://fixture.supabase.invalid",SUPABASE_API_KEY:"sb_secret_fixture_dedicated_key"},outboundService:async request=>{const body=await request.json();reads.push(body);assert.equal(request.url,"https://fixture.supabase.invalid/rest/v1/rpc/cloud_agent_visit_read");assert.equal(body.p_actor.tenantId,tenant);assert.equal(body.p_actor.rootMessageId,rootless?undefined:root);if(denied||body.p_actor.managerId!==manager)return new Response(null,{status:403});if(body.p_input.action==="patientSearch")return Response.json({mode:"test",kind:"patients",patients:[{id:patientId,label:"Synthetic selected person",reference:"TEST-001"}]});assert.equal(body.p_input.action,"visitSelect");const context={mode:"test",kind:"context",patient:{id:patientId,label:"Synthetic selected person",reference:"TEST-001",privateMarker:"DO_NOT_PROJECT"},reservations:[{id:otherReservation,at:"2026-01-02",type:"unlinked",status:"confirmed",procedureText:"UNLINKED_CANDIDATE",note:"UNLINKED_NOTE",pod:"UNLINKED_POD"},{id:reservationId,at:"2026-01-01",type:"consultation",status:changed?"changed":"confirmed",procedureText:"Synthetic linked candidate",note:"Synthetic linked note\nSecond line",pod:podChanged?"POD 4":"POD 3",privateMarker:"DO_NOT_PROJECT"}],visits:[{id:visitId,date:"2026-01-01",reservationId,status:"arrived"}],selectedVisitId:body.p_input.visitId,intake:{concernText:concernChanged?"Changed synthetic concern":"Synthetic intake concern",privateMarker:"DO_NOT_PROJECT"},performed:{procedureText:performedProcedureChanged?performed.procedureText+" revised":performed.procedureText,pod:performedPodChanged?"Synthetic procedure A (2025-12-25): POD 8\nSynthetic procedure A (2025-12-29): POD 4":performed.pod,privateMarker:"DO_NOT_PROJECT"},observedAt:new Date(1767225600000+(performedPodChanged?86400000:0)+observed++*1000).toISOString()};if(noVisits)context.visits=[];if(candidatesMissing){delete context.intake;delete context.performed;delete context.reservations[1].pod;}if(relinked){context.reservations[0]={...context.reservations[1],id:otherReservation};context.visits[0].reservationId=otherReservation;}return Response.json(context);}}
]});
const awaitModules=await piTextModules(resolve("build/pi"));let mf=new Miniflare(options());
const owner=async()=>{const ns=await mf.getDurableObjectNamespace("Credentials","cloud");return ns.get(ns.idFromName("owner"));};
const admin=async(action,input)=>{const response=await (await owner()).fetch("https://internal.invalid/fixture/admin",{method:"POST",body:JSON.stringify({action,input})});return {status:response.status,...await response.json()};};
const assistant=async(targetRoot=root)=>{const ns=await mf.getDurableObjectNamespace("Assistant","cloud");return ns.get(ns.idFromName("channel-"+hash(JSON.stringify([channel,group,targetRoot]))));};
const envelope=(method,params,caller=manager)=>({method,params,context:{channel:{id:channel},caller:{type:"manager",id:caller}}});
const call=async(input,signed=true)=>{const body=JSON.stringify(input);const response=await (await mf.getWorker("events")).fetch(origin+"/functions",{method:"PUT",body,headers:{"x-signature":signed?createHmac("sha256",Buffer.from(signing,"hex")).update(body).digest("base64"):"wrong"}});return {status:response.status,...await response.json()};};
const capability=async(targetRoot=root)=>(await call(envelope("commands.ai.open",{chat:{type:"group",id:group},trigger:{attributes:{rootMessageId:targetRoot}}}))).result.attributes.wamArgs.targetCapability;
let targetCapability;const request=input=>call(envelope("commands.ai.workflow",{targetCapability,...input}));
const prepare=async(name,revision,values,selection,finalText)=>(await request({action:"prepare",name,revision,values,...(selection?{selection}:{}),...(finalText===undefined?{}:{finalText})}));
const sendInput=(draft,name,revision,values,selection,finalText)=>({action:"send",name,revision,values,...(selection?{selection}:{}),...(finalText===undefined?{}:{finalText}),operationId:draft.operationId,draftToken:draft.draftToken,confirmed:true,confirmations:definitions[name].confirmations.map(row=>row.id)});
try{
for(const [name,bundle]of Object.entries(bundles)){assert.equal((await admin("skill.publish",bundle)).status,200);assert.equal((await admin("skill.toggle",{name,enabled:true})).status,200);}targetCapability=await capability();
const catalog=(await request({action:"catalog"})).result;assert.equal(catalog.workflows.length,2);const revisions=Object.fromEntries(catalog.workflows.map(row=>[row.name,row.revision]));const selection={patientId,visitId};
assert.equal((await call(envelope("commands.ai.workflow",{targetCapability,action:"catalog"}),false)).status,401);assert.ok((await call(envelope("commands.ai.workflow",{targetCapability,action:"catalog"},"another-manager"))).error);assert.equal((await request({action:"catalog",tenantId:"untrusted"})).error.message,"workflow_input_invalid");
const selected=(await request({action:"prefill",name:"visit-handoff",revision:revisions["visit-handoff"],selection})).result;assert.equal(selected.values.procedure,"Synthetic linked candidate");assert.equal(selected.values.note,"Synthetic linked note\nSecond line");assert.equal(selected.values.area,"Synthetic intake concern");assert.equal(selected.values.pod,"POD 3");assert.equal(selected.values.revision,"");assert.equal(selected.text,undefined,"Missing required staff values cannot seed a valid message");assert.ok(!JSON.stringify(selected).includes("UNLINKED")&&!JSON.stringify(selected).includes("DO_NOT_PROJECT"));
assert.equal(selected.values.performed_procedure,performed.procedureText);assert.equal(selected.values.performed_pod,performed.pod);
candidatesMissing=true;const missing=(await request({action:"prefill",name:"visit-handoff",revision:revisions["visit-handoff"],selection})).result;assert.equal(missing.values.area,"");assert.equal(missing.values.pod,"");assert.equal(missing.values.performed_procedure,"");assert.equal(missing.values.performed_pod,"");candidatesMissing=false;
const values={...selected.values,note:"Staff corrected synthetic candidate\nStaff second line",area:"Confirmed synthetic area",pod:"Staff corrected POD",performed_procedure:"Staff confirmed synthetic procedures",performed_pod:"Staff confirmed episode A: POD 7\nStaff confirmed episode B: POD 3",revision:"아니요",exceptions:"None"};
for(const [field,value]of [["person","Changed identity"],["date","2026-02-01"]])assert.equal((await prepare("visit-handoff",revisions["visit-handoff"],{...values,[field]:value},selection)).error.message,"workflow_values_invalid","Patient and visit identity stay immutable");const draft=(await prepare("visit-handoff",revisions["visit-handoff"],values,selection)).result;assert.match(draft.text,/Synthetic linked candidate/);assert.ok(draft.text.includes(values.note)&&draft.text.includes(values.area)&&draft.text.includes(values.pod),"Staff corrections and newlines survive exact rendering");const payload=JSON.parse(Buffer.from(draft.draftToken.split(".")[0],"base64url"));assert.ok(!JSON.stringify(payload).includes("Synthetic")&&!JSON.stringify(payload).includes(patientId));assert.equal(payload.operationId,draft.operationId);assert.ok(!JSON.stringify(payload).includes(values.area));
assert.ok(draft.text.includes(values.performed_procedure)&&draft.text.includes(values.performed_pod),"Staff can edit both performed summaries and retain all POD lines in the rendered message");
let send=sendInput(draft,"visit-handoff",revisions["visit-handoff"],values,selection);assert.equal((await request({...send,confirmations:[]})).error.message,"workflow_confirmation_required");assert.equal((await request({...send,confirmed:false})).error.message,"workflow_confirmation_required");assert.equal((await request({...send,operationId:randomUUID()})).error.message,"workflow_draft_expired_or_mismatched");assert.equal(writes.length,0);
concernChanged=true;assert.equal((await request(send)).error.message,"workflow_draft_changed","Intake changes invalidate the reviewed source even after staff edits");concernChanged=false;podChanged=true;assert.equal((await request(send)).error.message,"workflow_draft_changed","POD changes invalidate the reviewed source");podChanged=false;
performedProcedureChanged=true;assert.equal((await request(send)).error.message,"workflow_draft_changed","Performed procedure changes invalidate the source even after staff edits");performedProcedureChanged=false;performedPodChanged=true;assert.equal((await request(send)).error.message,"workflow_draft_changed","Performed POD changes invalidate the source even after staff edits");performedPodChanged=false;assert.equal(writes.length,0);
changed=true;assert.equal((await request(send)).error.message,"workflow_draft_changed");changed=false;relinked=true;assert.equal((await request(send)).error?.message,"workflow_draft_changed","A changed reservation link is stale even when every displayed source fact matches");relinked=false;denied=true;assert.equal((await request(send)).error.message,"visit_record_denied");denied=false;
const editedReply="  Authored reply heading\nOnly staff-chosen body <img src=x>  ";const preparedAgain=(await prepare("visit-handoff",revisions["visit-handoff"],values,selection,editedReply)).result;assert.equal(preparedAgain.text,editedReply);send=sendInput(preparedAgain,"visit-handoff",revisions["visit-handoff"],values,selection,editedReply);for(const finalText of [undefined,editedReply+" changed"])assert.equal((await request({...send,finalText})).error.message,"workflow_draft_changed");const delivered=(await request(send)).result;assert.equal(delivered.status,"sent");assert.equal(writes.length,1);assert.equal(writes[0].dto.plainText,editedReply);assert.equal(writes[0].rootMessageId,root);changed=true;denied=true;const beforeReplayReads=reads.length;assert.deepEqual((await request(send)).result,delivered);assert.equal(reads.length,beforeReplayReads);assert.equal(writes.length,1);assert.equal((await request({...send,values:{...values,area:"Changed field"}})).error.message,"workflow_draft_changed");for(const finalText of [undefined,editedReply+" changed"])assert.equal((await request({...send,finalText})).error.message,"workflow_draft_changed","Authored text presence and bytes remain bound before replay");denied=false;changed=false;
const wrongRoot=await capability("other-root");assert.equal((await call(envelope("commands.ai.workflow",{targetCapability:wrongRoot,action:"status",operationId:send.operationId,draftToken:send.draftToken}))).error.message,"workflow_draft_expired_or_mismatched");
const newBundle={...bundles["visit-handoff"],resources:[{...bundles["visit-handoff"].resources[0],content:JSON.stringify({...definitions["visit-handoff"],title:"New title",template:"New template {{person}} {{area}} {{revision}} {{exceptions}}"})}]};assert.equal((await admin("skill.publish",newBundle)).status,200);assert.equal((await prepare("visit-handoff",revisions["visit-handoff"],values,selection)).error.message,"workflow_skill_unavailable");await admin("skill.toggle",{name:"visit-handoff",enabled:true});const pinned=(await prepare("visit-handoff",revisions["visit-handoff"],values,selection,editedReply)).result;assert.equal(pinned.text,preparedAgain.text,"Opened revision remains pinned after a new publication");await admin("skill.toggle",{name:"visit-handoff",enabled:false});assert.equal((await request(sendInput(pinned,"visit-handoff",revisions["visit-handoff"],values,selection,editedReply))).error.message,"workflow_skill_unavailable");assert.deepEqual((await request({action:"status",operationId:send.operationId,draftToken:send.draftToken})).result,delivered);
const manualValues={audience:"운영팀",notice:"Synthetic notice",when:"Tomorrow"},beforeManual=reads.length;const manualPrefill=(await request({action:"prefill",name:"staff-notice",revision:revisions["staff-notice"]})).result;assert.equal(manualPrefill.values.audience,"");const manualDraft=(await prepare("staff-notice",revisions["staff-notice"],manualValues)).result;const manualSend=sendInput(manualDraft,"staff-notice",revisions["staff-notice"],manualValues);writeMode="unknown";const uncertain=(await request(manualSend)).result;assert.equal(uncertain.status,"uncertain");assert.equal(writes.length,2);assert.deepEqual((await request(manualSend)).result,uncertain);assert.equal(reads.length,beforeManual,"Manual workflows never read the visit database");assert.equal(writes.length,2);
await mf.dispose();mf=new Miniflare(options());assert.deepEqual((await request(send)).result,delivered);assert.deepEqual((await request(manualSend)).result,uncertain);assert.equal(writes.length,2,"Cold restart never resends completed or uncertain work");
const serverErrorDraft=(await prepare("staff-notice",revisions["staff-notice"],manualValues)).result,serverErrorInput=sendInput(serverErrorDraft,"staff-notice",revisions["staff-notice"],manualValues);writeMode="server-error";const serverErrorReceipt=(await request(serverErrorInput)).result;assert.equal(serverErrorReceipt.status,"uncertain","HTTP500 may follow provider-side delivery and must not be treated as a safe rejection");assert.equal(writes.length,3);assert.deepEqual((await request(serverErrorInput)).result,serverErrorReceipt);assert.equal(writes.length,3);
const stagedDraft=(await prepare("staff-notice",revisions["staff-notice"],manualValues)).result,stagedPayload=JSON.parse(Buffer.from(stagedDraft.draftToken.split(".")[0],"base64url")),stagedActor=await assistant();await stagedActor.fetch("https://internal.invalid/fixture/stage",{method:"POST",body:JSON.stringify({operationId:stagedDraft.operationId,requestDigest:hash(JSON.stringify(stagedPayload))})});await mf.dispose();mf=new Miniflare(options());const stagedReceipt=(await request(sendInput(stagedDraft,"staff-notice",revisions["staff-notice"],manualValues))).result;assert.equal(stagedReceipt.status,"uncertain");assert.equal(writes.length,3,"A restarted sending claim is uncertain and never resent");
const actor=await assistant(),inspect=await (await actor.fetch("https://internal.invalid/fixture/inspect")).json();assert.equal(inspect.modelCalls,0);assert.equal(inspect.commandRows,0);assert.equal(inspect.channelRows,0);assert.deepEqual(inspect.runtime,[]);assert.ok(!JSON.stringify(inspect.rows).includes("Synthetic")&&!JSON.stringify(inspect.rows).includes(patientId));for(const row of inspect.rows)assert.deepEqual(Object.keys(row).sort(),[...(row.finalTextHash?["finalTextHash"]:[]),"key",...(row.replyId?["replyId"]:[]),"requestDigest","state"]);
const internalTarget={channelId:channel,groupId:group,rootMessageId:root,managerId:manager};const conflict=await (await actor.fetch("https://internal.invalid/fixture/status",{method:"POST",body:JSON.stringify({target:internalTarget,operationId:send.operationId,requestDigest:"00".repeat(32)})})).json();assert.equal(conflict.error,"workflow_operation_conflict");const spoof=await (await actor.fetch("https://internal.invalid/fixture/status",{method:"POST",body:JSON.stringify({target:{...internalTarget,tenantId:"other"},operationId:send.operationId,requestDigest:"00".repeat(32)})})).json();assert.equal(spoof.error,"visit_target_invalid");const wrongActor=await (await actor.fetch("https://internal.invalid/fixture/status",{method:"POST",body:JSON.stringify({target:{...internalTarget,rootMessageId:"another-root"},operationId:send.operationId,requestDigest:"00".repeat(32)})})).json();assert.equal(wrongActor.error,"workflow_actor_mismatch");
const replyPayload=JSON.parse(Buffer.from(preparedAgain.draftToken.split(".")[0],"base64url")),replyRpc={target:internalTarget,operationId:send.operationId,requestDigest:hash(JSON.stringify(replyPayload)),name:send.name,revision:send.revision,values,source:null,finalText:editedReply,textHash:hash(editedReply),confirmed:true};
for(const patch of [{finalText:undefined},{finalText:editedReply+" changed"},{finalText:" \n"},{textHash:"0".repeat(64)},{finalText:editedReply+" changed",textHash:hash(editedReply+" changed")}])assert.match((await(await actor.fetch("https://internal.invalid/fixture/send",{method:"POST",body:JSON.stringify({...replyRpc,...patch})})).json()).error,/workflow_(draft_changed|final_text_invalid)/);
assert.deepEqual(await(await actor.fetch("https://internal.invalid/fixture/send",{method:"POST",body:JSON.stringify(replyRpc)})).json(),delivered);assert.equal(writes.length,3);
const db=await mf.getD1Database("CONVERSATIONS","cloud"),tables=await db.prepare("SELECT name FROM sqlite_master WHERE name LIKE 'ca_%'").all();for(const name of ["ca_asks","ca_entries","ca_channel_messages","ca_command_receipts"])if(tables.results.some(row=>row.name===name))assert.equal((await db.prepare(`SELECT COUNT(*) AS n FROM ${name}`).first()).n,0,"Workflow content never enters generic D1 conversation records");
await mf.dispose();mf=new Miniflare(options("another-fixture-tenant"));assert.ok((await request({action:"catalog"})).error,"Existing owner and Assistant reject a deployment tenant change");assert.equal(writes.length,3);
const invalid={...bundles["staff-notice"],resources:[{...bundles["staff-notice"].resources[0],content:'{"schemaVersion":999}'}]};await mf.dispose();mf=new Miniflare(options());assert.equal((await admin("skill.publish",invalid)).error,"workflow_definition_invalid");

rootless=true;await mf.dispose();mf=new Miniflare(options());await admin("skill.toggle",{name:"visit-handoff",enabled:true});writeMode="sent";
const launch=async()=>(await call(envelope("commands.ai.open",{chat:{type:"group",id:group}}))).result.attributes.wamArgs.targetCapability;
const intent={modelId:"gpt-6.1-sol",thinkingLevel:"high"};
targetCapability=await launch();const originalCapability=targetCapability,baselineWrites=writes.length;
const groupCatalog=(await request({action:"catalog"})).result;assert.equal(groupCatalog.workflows.length,2,"Rootless catalog requires no Assistant binding");
assert.equal((await call(envelope("commands.ai.visit",{targetCapability,action:"patientSearch",query:"Synthetic"}))).result.kind,"patients");
const groupPrefill=(await request({action:"prefill",name:"visit-handoff",revision:revisions["visit-handoff"],selection})).result;
const groupValues={...groupPrefill.values,area:"Edited root concern\nSecond line",pod:"Edited POD",revision:"아니요",exceptions:"None",note:"Edited root note"};
const editedRoot="  Staff-authored first message\nRemoved template lines; a new heading\nExact final line <img src=x>  ";
const groupPrepare={finalText:editedRoot,action:"prepare",name:"visit-handoff",revision:revisions["visit-handoff"],selection,values:groupValues,intent};
assert.equal((await request({...groupPrepare,intent:undefined})).error.message,"workflow_input_invalid");
let groupDraft=(await request(groupPrepare)).result,groupSend={...sendInput(groupDraft,"visit-handoff",revisions["visit-handoff"],groupValues,selection,editedRoot),intent};
assert.equal(writes.length,baselineWrites,"Search, prefill, edits and review cannot write a placeholder");
const groupPayload=JSON.parse(Buffer.from(groupDraft.draftToken.split(".")[0],"base64url"));assert.equal(groupPayload.delivery,"root");assert.ok(!JSON.stringify(groupPayload).includes(patientId)&&!JSON.stringify(groupPayload).includes(groupValues.area));
for(const patch of [{finalText:undefined},{finalText:editedRoot+" changed"},{intent:{...intent,thinkingLevel:"low"}},{intent:{...intent,modelId:"different-model"}},{values:{...groupValues,note:"Changed text"}},{selection:{...selection,visitId:otherReservation}},{revision:"0".repeat(64)}])assert.equal((await request({...groupSend,...patch})).error.message,"workflow_draft_changed");
assert.equal((await request({...groupSend,plainText:"Unchecked browser message"})).error.message,"workflow_input_invalid");
assert.equal((await request({...groupSend,confirmations:[]})).error.message,"workflow_confirmation_required");
assert.equal((await request({...groupSend,confirmed:false})).error.message,"workflow_confirmation_required");
assert.equal((await request({...groupSend,draftToken:groupSend.draftToken.slice(0,-2)+"aa"})).error.message,"workflow_draft_invalid");
targetCapability=await launch();assert.equal((await request(groupSend)).error.message,"workflow_draft_expired_or_mismatched");targetCapability=originalCapability;
assert.ok((await call(envelope("commands.ai.workflow",{targetCapability,...groupSend},"different-manager"))).error);
concernChanged=true;assert.equal((await request(groupSend)).error.message,"workflow_draft_changed");concernChanged=false;
relinked=true;assert.equal((await request(groupSend)).error.message,"workflow_draft_changed");relinked=false;
denied=true;assert.equal((await request(groupSend)).error.message,"visit_record_denied");denied=false;
assert.equal(writes.length,baselineWrites);
const forbiddenModel={...intent,modelId:"fixture-withdrawn-model"},forbiddenDraft=(await request({...groupPrepare,intent:forbiddenModel})).result;
assert.equal((await request({...sendInput(forbiddenDraft,"visit-handoff",revisions["visit-handoff"],groupValues,selection,editedRoot),intent:forbiddenModel})).error.message,"command_start_model_not_permitted");
assert.equal(writes.length,baselineWrites,"A withdrawn model is rejected before claiming or writing a root");
const concurrent=await Promise.all([request(groupSend),request(groupSend)]);assert.ok(concurrent.some(row=>row.result.status==="ready"));assert.equal(writes.length,baselineWrites+1);
const groupStatus={action:"status",operationId:groupSend.operationId,draftToken:groupSend.draftToken},rootResult=(await request(groupStatus)).result;
assert.equal(rootResult.status,"ready");assert.equal(rootResult.rootAvailable,true);assert.ok(rootResult.targetCapability);assert.equal(groupDraft.text,editedRoot);assert.equal(writes.at(-1).dto.plainText,editedRoot);assert.ok(!Object.hasOwn(writes.at(-1),"rootMessageId"));assert.ok(!writes.at(-1).dto.plainText.includes("업무를 시작합니다"));
const startRows=await(await(await owner()).fetch("https://internal.invalid/fixture/inspect")).json();assert.deepEqual(startRows.threads,[]);assert.equal(startRows.cursor,0);assert.equal(startRows.starts.length,1);assert.deepEqual(startRows.preferences.find(row=>row.target.rootMessageId===rootResult.rootMessageId)?.intent,{...intent,workflow:{name:"visit-handoff",revision:revisions["visit-handoff"]}});assert.ok(!JSON.stringify(startRows).includes(groupValues.area)&&!JSON.stringify(startRows).includes(patientId));assert.equal(startRows.starts[0].target.nonce,JSON.parse(Buffer.from(originalCapability.split(".")[0],"base64url")).nonce);
assert.ok(!JSON.stringify(startRows).includes(editedRoot),"Root receipts never contain the authored body");
const rootRpc={target:startRows.starts[0].target,operationId:groupSend.operationId,intent:{...intent,workflow:{name:groupSend.name,revision:groupSend.revision}},confirmed:true,reviewedWorkflow:{reviewDigest:hash(JSON.stringify(groupPayload)),textHash:hash(editedRoot),values:groupValues,source:null,finalText:editedRoot}};
for(const patch of [{finalText:undefined},{finalText:editedRoot+" changed"},{finalText:" \n"},{textHash:"0".repeat(64)},{finalText:editedRoot+" changed",textHash:hash(editedRoot+" changed")}])assert.match((await(await(await owner()).fetch("https://internal.invalid/fixture/start",{method:"POST",body:JSON.stringify({...rootRpc,reviewedWorkflow:{...rootRpc.reviewedWorkflow,...patch}})})).json()).error,/workflow_(draft_changed|final_text_invalid)|command_start_operation_conflict/);
assert.equal((await(await(await owner()).fetch("https://internal.invalid/fixture/start",{method:"POST",body:JSON.stringify(rootRpc)})).json()).status,"ready");
const beforeReplay=reads.length;denied=true;assert.deepEqual((await request(groupSend)).result,rootResult);for(const finalText of [undefined,editedRoot+" changed"])assert.equal((await request({...groupSend,finalText})).error.message,"workflow_draft_changed");assert.equal(reads.length,beforeReplay);denied=false;
await mf.dispose();mf=new Miniflare(options());assert.deepEqual((await request(groupStatus)).result,rootResult);assert.deepEqual((await(await(await owner()).fetch("https://internal.invalid/fixture/inspect")).json()).preferences.find(row=>row.target.rootMessageId===rootResult.rootMessageId)?.intent,{...intent,workflow:{name:"visit-handoff",revision:revisions["visit-handoff"]}},"Cold restart retains model, thinking and exact workflow revision for the real root");assert.equal(writes.length,baselineWrites+1);
const anotherDraft=(await request(groupPrepare)).result;assert.equal((await request({...sendInput(anotherDraft,"visit-handoff",revisions["visit-handoff"],groupValues,selection,editedRoot),intent})).error.message,"command_start_launch_used");
for(const failure of ["unknown","server-error","cross-group","thread"]){
  targetCapability=await launch();const manualPrepare={finalText:exactText,action:"prepare",name:"staff-notice",revision:revisions["staff-notice"],values:manualValues,intent},manualRootDraft=(await request(manualPrepare)).result,manualRootSend={...sendInput(manualRootDraft,"staff-notice",revisions["staff-notice"],manualValues,undefined,exactText),intent};
  const before=writes.length,beforeReads=reads.length;writeMode=failure;assert.equal((await request(manualRootSend)).result.status,"uncertain");assert.equal(writes.length,before+1);assert.equal(writes.at(-1).dto.plainText,manualRootDraft.text);
  await mf.dispose();mf=new Miniflare(options());assert.equal((await request(manualRootSend)).result.status,"uncertain");assert.equal((await request({action:"status",operationId:manualRootSend.operationId,draftToken:manualRootSend.draftToken})).result.status,"uncertain");for(const finalText of [undefined,exactText+" changed"])assert.equal((await request({...manualRootSend,finalText})).error.message,"workflow_draft_changed");assert.equal(writes.length,before+1);assert.equal(reads.length,beforeReads,"Manual root sends and recovery never read business data");
  const recovery=failure==="unknown"?{operationId:manualRootSend.operationId,action:"bind",rootMessageId:"fixture-reviewed-native-root",confirmed:true}:{operationId:manualRootSend.operationId,action:"abandon",confirmed:true};assert.equal((await admin("command-start.recover",recovery)).status,failure==="unknown"?"ready":"abandoned");
  assert.equal((await request({action:"status",operationId:manualRootSend.operationId,draftToken:manualRootSend.draftToken})).result.status,failure==="unknown"?"ready":"abandoned");assert.equal(writes.length,before+1,"Admin recovery finishes the existing receipt without resend");
}
const fixedBundle={...bundles["staff-notice"],resources:[{...bundles["staff-notice"].resources[0],content:JSON.stringify({schemaVersion:1,title:"Fixture fixed notice",source:"none",fields:[],template:"Synthetic fixed message",confirmations:[]})}]};assert.equal((await admin("skill.publish",fixedBundle)).status,200);await admin("skill.toggle",{name:"staff-notice",enabled:true});const fixed=(await request({action:"catalog"})).result.workflows.find(row=>row.name==="staff-notice");assert.equal((await request({action:"prefill",name:fixed.name,revision:fixed.revision})).result.text,"Synthetic fixed message","Complete source-free prefills seed the full message without creating a review or send");
for (const rootMode of [false,true]) {
  rootless=rootMode;await mf.dispose();mf=new Miniflare(options());writeMode="sent";
  for (const noScheduleRecords of [true,false]) {
    noVisits=noScheduleRecords;targetCapability=rootless?await launch():await capability();const patientSelection={patientId,visitId:null};
    const patientPrefill=(await request({action:"prefill",name:"visit-handoff",revision:revisions["visit-handoff"],selection:{patientId}})).result;
    assert.equal(patientPrefill.values.person,"Synthetic selected person");assert.equal(patientPrefill.values.area,"Synthetic intake concern");for(const field of ["date","procedure","note","pod"])assert.equal(patientPrefill.values[field],"","No unselected visit or reservation candidate enters the form");
    assert.equal(patientPrefill.values.performed_procedure,performed.procedureText);assert.equal(patientPrefill.values.performed_pod,performed.pod,"All labelled patient-level POD lines prefill without a schedule");
    const patientValues={...patientPrefill.values,revision:"아니요",exceptions:"None"},body="  Patient-only edited message\nExact staff text  ";
    const patientPrepare={action:"prepare",name:"visit-handoff",revision:revisions["visit-handoff"],selection:{patientId},values:patientValues,finalText:body,...(rootless?{intent}:{})};
    const patientDraft=(await request(patientPrepare)).result;assert.equal(patientDraft.text,body);const patientSend={...sendInput(patientDraft,"visit-handoff",revisions["visit-handoff"],patientValues,patientSelection,body),...(rootless?{intent}:{})},beforeWrites=writes.length;
    assert.equal((await request({...patientSend,selection:{patientId,visitId}})).error.message,"workflow_draft_changed");
    assert.equal((await request({...patientSend,finalText:body+" changed"})).error.message,"workflow_draft_changed");
    concernChanged=true;assert.equal((await request(patientSend)).error.message,"workflow_draft_changed","Patient-level intake changes invalidate a reviewed patient-only message");concernChanged=false;
    performedProcedureChanged=true;assert.equal((await request(patientSend)).error.message,"workflow_draft_changed","Patient-only review includes the exact performed procedure summary");performedProcedureChanged=false;
    performedPodChanged=true;assert.equal((await request(patientSend)).error.message,"workflow_draft_changed","A new day's performed POD summary invalidates patient-only review before any send");performedPodChanged=false;
    denied=true;assert.equal((await request(patientSend)).error.message,"visit_record_denied","Patient-only delivery rechecks current access");denied=false;assert.equal(writes.length,beforeWrites);
    changed=true;relinked=!noVisits;const sendResult=await request(patientSend);assert.equal(sendResult.error,undefined,JSON.stringify(sendResult));const sent=sendResult.result;changed=false;relinked=false;
    assert.equal(sent.status,rootless?"ready":"sent");assert.equal(writes.length,beforeWrites+1);assert.equal(writes.at(-1).dto.plainText,body);assert.equal(writes.at(-1).rootMessageId,rootless?undefined:root,"Exact edited patient-only text reaches the selected destination");
    denied=true;const beforeReads=reads.length;assert.deepEqual((await request({...patientSend,selection:{patientId}})).result,sent,"Omitted/null schedule normalization also applies before replay");assert.equal(reads.length,beforeReads);assert.equal(writes.length,beforeWrites+1);denied=false;
  }
}
noVisits=false;
console.log("Workflow checks passed: patient-only null/omitted selections, patient intake and no invented schedule, exact patient-only root/reply send, revoked/changed sources, authored full text bounds and exact root/reply delivery, text presence/byte tampering before replay, ready and uncertain no-resend, two reusable customer forms, selected linked reservation projection, digest-only operation-bound draft, reauthorization/source refresh, revision pin and disable, manual no-DB, exact-root native send, replay/conflict/cold restart/uncertain, tenant spoof guards, reviewed root-first form delivery without an Assistant binding, settings/nonce/replay guards, root recovery and no model or clinical transcript effects.");
}finally{await mf.dispose();await rm(persistence,{recursive:true,force:true});}
