import assert from "node:assert/strict";
import { createHash, createHmac, randomBytes, randomUUID } from "node:crypto";
import { mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Miniflare, convertV4MiniflareOptions } from "miniflare";
import { piTextModules } from "./pi-modules.mjs";
import { workflowDefinition, workflowFromSkill } from "../../workers/pi/workflow.js";
process.chdir(fileURLToPath(new URL("../..", import.meta.url)));
const channel="fixture-channel",group="fixture-group",root="fixture-root",manager="fixture-manager",origin="https://events.example.invalid",signing="ab".repeat(32),token="fixture-visit-token-at-least-32-characters";
const patientId="10000000-0000-0000-0000-000000000001",visitId="20000000-0000-0000-0000-000000000001",reservationId="30000000-0000-0000-0000-000000000001",otherReservation="30000000-0000-0000-0000-000000000002";
const hash=value=>createHash("sha256").update(value).digest("hex"),persistence=await mkdtemp(join(tmpdir(),"workflow-check-")),wrapping=randomBytes(32).toString("base64url");
const definitions={};const bundles={};for(const name of ["visit-handoff","staff-notice"]){const rawContent=await readFile(`skills/workflows/${name}/SKILL.md`,"utf8"),content=await readFile(`skills/workflows/${name}/references/workflow.json`,"utf8");const definition=JSON.parse(content);if(name==="visit-handoff"){definition.fields.find(field=>field.id==="area").source="intake.concernText";definition.fields.push({id:"pod",label:"POD",type:"text",required:false,maxLength:40,source:"reservation.pod"});definition.template+="\nPOD: {{pod}}";}definitions[name]=workflowDefinition(definition);bundles[name]={rawContent,resources:[{path:"references/workflow.json",kind:"reference",content:JSON.stringify(definition)}]};}
for(const mutate of [d=>({...d,schemaVersion:2}),d=>({...d,tenant:"untrusted"}),d=>({...d,template:"{{person.toUpperCase()}}"}),d=>({...d,template:"https://untrusted.invalid"}),d=>({...d,fields:[{...d.fields[0],source:"reservation.sql"}]}),d=>({...d,fields:Array(21).fill(d.fields[0])}),d=>({...d,confirmations:Array(11).fill(d.confirmations[0])})])assert.throws(()=>workflowDefinition(mutate(definitions["visit-handoff"])),/workflow_definition_invalid/);
assert.equal(workflowDefinition({schemaVersion:1,title:"Fixture fixed notice",source:"none",fields:[],template:"Fixture notice",confirmations:[]}).fields.length,0);
assert.throws(()=>workflowFromSkill({resources:[{path:"references/workflow.json",content:"{"}]}),/workflow_definition_invalid/);
await writeFile("build/pi/workflow-wrapper.js",`import worker,{Assistant as BaseAssistant,Credentials as BaseCredentials} from './index.js';export default worker;
export class Assistant extends BaseAssistant{async fetch(request){const path=new URL(request.url).pathname;if(path==='/fixture/inspect')return Response.json({rows:[...await this.ctx.storage.list({prefix:'workflow-delivery:'})].map(([key,value])=>({key,...value})),commandRows:this.channelSql.exec('SELECT COUNT(*) AS n FROM command_operations').toArray()[0].n,channelRows:this.channelSql.exec('SELECT COUNT(*) AS n FROM channel_messages').toArray()[0].n,runtime:this.channelSql.exec('SELECT data FROM channel_runtime').toArray(),modelCalls:this.faux.state.callCount});if(path==='/fixture/status'){const input=await request.json();try{return Response.json(await this.workflowStatus(input.target,input.operationId,input.requestDigest));}catch(error){return Response.json({error:error.message});}}if(path==='/fixture/stage'){const input=await request.json();await this.ctx.storage.put('workflow-delivery:'+input.operationId,{requestDigest:input.requestDigest,state:'sending'});return Response.json({ok:true});}if(path==='/fixture/send'){try{return Response.json(await this.workflowSend(await request.json()));}catch(error){return Response.json({error:error.message});}}return new Response(null,{status:404});}}
export class Credentials extends BaseCredentials{async adminSession(){return {principal:{email:'fixture-admin@example.invalid',role:'super_admin'},csrf:'fixture-csrf'};}async channelAccess(){return 'fixture-native-access';}async fetch(request){if(new URL(request.url).pathname==='/fixture/admin'){const input=await request.json();try{return Response.json(await this.adminMutation(input.action,input.input,'fixture-session','fixture-csrf'));}catch(error){return Response.json({error:error.message},{status:400});}}return new Response(null,{status:404});}}
`);
let changed=false,relinked=false,denied=false,candidatesMissing=false,concernChanged=false,podChanged=false,writeMode="sent",observed=0;const reads=[],writes=[];
const options=(tenant="fixture-tenant")=>convertV4MiniflareOptions({resourcePersistencePath:persistence,workers:[
{name:"events",modulesRoot:resolve("build/events"),modules:[{type:"ESModule",path:resolve("build/events/index.js")}],compatibilityDate:"2026-10-01",compatibilityFlags:["nodejs_compat","global_fetch_strictly_public"],kvNamespaces:["OAUTH_KV"],durableObjects:{EVENTS:{className:"ChannelEvents",useSQLite:true},THREADS:{className:"ThreadHistory",useSQLite:true},PI_ASSISTANT:{className:"Assistant",scriptName:"cloud",useSQLite:true}},serviceBindings:{VISIT_API:"visit"},bindings:{PUBLIC_ORIGIN:origin,EVENTS_OBJECT_NAME:"fixture-events",OAUTH_OWNER_ID:"fixture-owner",CHANNEL_SLUG:"fixture-channel",CHANNEL_APP_SIGNING_KEY:signing,ALLOWED_CHANNEL_ID:channel,ALLOWED_CHAT_ID:group,CHANNEL_APP_ID:"fixture-app",COMMAND_GROUP_IDS:JSON.stringify([group]),COMMAND_PRIVATE_MANAGERS:"{}",VISIT_SERVICE_TOKEN:token},outboundService:()=>assert.fail("Events has no arbitrary outbound workflow calls")},
{name:"cloud",modulesRoot:resolve("build/pi"),modules:[...["workflow-wrapper.js","index.js"].map(name=>({type:"ESModule",path:resolve("build/pi",name)})),...awaitModules],compatibilityDate:"2026-10-04",compatibilityFlags:["nodejs_compat","global_fetch_strictly_public"],d1Databases:["CONVERSATIONS"],durableObjects:{Assistant:{className:"Assistant",useSQLite:true},Credentials:{className:"Credentials",useSQLite:true}},bindings:{TENANT_ID:tenant,TOKEN_WRAPPING_KEY:wrapping,TOKEN_WRAPPING_AAD:"fixture/v1",PROBE_MODE:"mock",OPENAI_MODEL:"gpt-6.1-sol",ALLOWED_CHANNEL_ID:channel,ALLOWED_CHAT_ID:group,CHANNEL_APP_ID:"fixture-app",COMMAND_GROUP_IDS:JSON.stringify([group]),COMMAND_PRIVATE_MANAGERS:"{}",VISIT_MCP_GROUP_ID:group,CHANNEL_REPLY_ENABLED:"true",PUBLIC_ORIGIN:"https://cloud.example.invalid"},outboundService:async request=>{assert.equal(request.url,"https://app-store-api.channel.io/general/v1/native/functions");assert.equal(request.method,"PUT");assert.equal(request.headers.get("x-access-token"),"fixture-native-access");const body=await request.json();assert.equal(body.method,"writeGroupMessage");assert.equal(body.params.channelId,channel);assert.equal(body.params.groupId,group);assert.equal(body.params.rootMessageId,root);assert.equal(body.params.broadcast,false);assert.match(body.params.dto.requestId,/^wfl-[a-f0-9-]{36}$/);assert.ok(!body.params.dto.files);writes.push(body.params);if(writeMode==="unknown")throw Error("fixture_lost_native_response");if(writeMode==="server-error")return Response.json({error:{message:"fixture_backend_error"}},{status:500});return Response.json({result:{message:{id:"fixture-reply-"+writes.length}}});}},
{name:"visit",modulesRoot:resolve("build/visit"),modules:[{type:"ESModule",path:resolve("build/visit/index.js")}],compatibilityDate:"2026-10-01",bindings:{TENANT_ID:tenant,VISIT_SERVICE_TOKEN:token,SUPABASE_URL:"https://fixture.supabase.invalid",SUPABASE_API_KEY:"sb_secret_fixture_dedicated_key"},outboundService:async request=>{const body=await request.json();reads.push(body);assert.equal(request.url,"https://fixture.supabase.invalid/rest/v1/rpc/cloud_agent_visit_read");assert.equal(body.p_actor.tenantId,tenant);assert.equal(body.p_actor.rootMessageId,root);if(denied||body.p_actor.managerId!==manager)return new Response(null,{status:403});assert.equal(body.p_input.action,"visitSelect");const context={mode:"test",kind:"context",patient:{id:patientId,label:"Synthetic selected person",reference:"TEST-001",privateMarker:"DO_NOT_PROJECT"},reservations:[{id:otherReservation,at:"2026-01-02",type:"unlinked",status:"confirmed",procedureText:"UNLINKED_CANDIDATE",note:"UNLINKED_NOTE",pod:"UNLINKED_POD"},{id:reservationId,at:"2026-01-01",type:"consultation",status:changed?"changed":"confirmed",procedureText:"Synthetic linked candidate",note:"Synthetic linked note\nSecond line",pod:podChanged?"POD 4":"POD 3",privateMarker:"DO_NOT_PROJECT"}],visits:[{id:visitId,date:"2026-01-01",reservationId,status:"arrived"}],selectedVisitId:body.p_input.visitId,intake:{concernText:concernChanged?"Changed synthetic concern":"Synthetic intake concern",privateMarker:"DO_NOT_PROJECT"},observedAt:new Date(1767225600000+observed++*1000).toISOString()};if(candidatesMissing){delete context.intake;delete context.reservations[1].pod;}if(relinked){context.reservations[0]={...context.reservations[1],id:otherReservation};context.visits[0].reservationId=otherReservation;}return Response.json(context);}}
]});
const awaitModules=await piTextModules(resolve("build/pi"));let mf=new Miniflare(options());
const owner=async()=>{const ns=await mf.getDurableObjectNamespace("Credentials","cloud");return ns.get(ns.idFromName("owner"));};
const admin=async(action,input)=>{const response=await (await owner()).fetch("https://internal.invalid/fixture/admin",{method:"POST",body:JSON.stringify({action,input})});return {status:response.status,...await response.json()};};
const assistant=async(targetRoot=root)=>{const ns=await mf.getDurableObjectNamespace("Assistant","cloud");return ns.get(ns.idFromName("channel-"+hash(JSON.stringify([channel,group,targetRoot]))));};
const envelope=(method,params,caller=manager)=>({method,params,context:{channel:{id:channel},caller:{type:"manager",id:caller}}});
const call=async(input,signed=true)=>{const body=JSON.stringify(input);const response=await (await mf.getWorker("events")).fetch(origin+"/functions",{method:"PUT",body,headers:{"x-signature":signed?createHmac("sha256",Buffer.from(signing,"hex")).update(body).digest("base64"):"wrong"}});return {status:response.status,...await response.json()};};
const capability=async(targetRoot=root)=>(await call(envelope("commands.ai.open",{chat:{type:"group",id:group},trigger:{attributes:{rootMessageId:targetRoot}}}))).result.attributes.wamArgs.targetCapability;
let targetCapability;const request=input=>call(envelope("commands.ai.workflow",{targetCapability,...input}));
const prepare=async(name,revision,values,selection)=>(await request({action:"prepare",name,revision,values,...(selection?{selection}:{})}));
const sendInput=(draft,name,revision,values,selection)=>({action:"send",name,revision,values,...(selection?{selection}:{}),operationId:draft.operationId,draftToken:draft.draftToken,confirmed:true,confirmations:definitions[name].confirmations.map(row=>row.id)});
try{
for(const [name,bundle]of Object.entries(bundles)){assert.equal((await admin("skill.publish",bundle)).status,200);assert.equal((await admin("skill.toggle",{name,enabled:true})).status,200);}targetCapability=await capability();
const catalog=(await request({action:"catalog"})).result;assert.equal(catalog.workflows.length,2);const revisions=Object.fromEntries(catalog.workflows.map(row=>[row.name,row.revision]));const selection={patientId,visitId};
assert.equal((await call(envelope("commands.ai.workflow",{targetCapability,action:"catalog"}),false)).status,401);assert.ok((await call(envelope("commands.ai.workflow",{targetCapability,action:"catalog"},"another-manager"))).error);assert.equal((await request({action:"catalog",tenantId:"untrusted"})).error.message,"workflow_input_invalid");
const selected=(await request({action:"prefill",name:"visit-handoff",revision:revisions["visit-handoff"],selection})).result;assert.equal(selected.values.procedure,"Synthetic linked candidate");assert.equal(selected.values.note,"Synthetic linked note\nSecond line");assert.equal(selected.values.area,"Synthetic intake concern");assert.equal(selected.values.pod,"POD 3");assert.equal(selected.values.revision,"");assert.ok(!JSON.stringify(selected).includes("UNLINKED")&&!JSON.stringify(selected).includes("DO_NOT_PROJECT"));
candidatesMissing=true;const missing=(await request({action:"prefill",name:"visit-handoff",revision:revisions["visit-handoff"],selection})).result;assert.equal(missing.values.area,"");assert.equal(missing.values.pod,"");candidatesMissing=false;
const values={...selected.values,note:"Staff corrected synthetic candidate\nStaff second line",area:"Confirmed synthetic area",pod:"Staff corrected POD",revision:"아니요",exceptions:"None"};
for(const [field,value]of [["person","Changed identity"],["date","2026-02-01"]])assert.equal((await prepare("visit-handoff",revisions["visit-handoff"],{...values,[field]:value},selection)).error.message,"workflow_values_invalid","Patient and visit identity stay immutable");const draft=(await prepare("visit-handoff",revisions["visit-handoff"],values,selection)).result;assert.match(draft.text,/Synthetic linked candidate/);assert.ok(draft.text.includes(values.note)&&draft.text.includes(values.area)&&draft.text.includes(values.pod),"Staff corrections and newlines survive exact rendering");const payload=JSON.parse(Buffer.from(draft.draftToken.split(".")[0],"base64url"));assert.ok(!JSON.stringify(payload).includes("Synthetic")&&!JSON.stringify(payload).includes(patientId));assert.equal(payload.operationId,draft.operationId);assert.ok(!JSON.stringify(payload).includes(values.area));
let send=sendInput(draft,"visit-handoff",revisions["visit-handoff"],values,selection);assert.equal((await request({...send,confirmations:[]})).error.message,"workflow_confirmation_required");assert.equal((await request({...send,confirmed:false})).error.message,"workflow_confirmation_required");assert.equal((await request({...send,operationId:randomUUID()})).error.message,"workflow_draft_expired_or_mismatched");assert.equal(writes.length,0);
concernChanged=true;assert.equal((await request(send)).error.message,"workflow_draft_changed","Intake changes invalidate the reviewed source even after staff edits");concernChanged=false;podChanged=true;assert.equal((await request(send)).error.message,"workflow_draft_changed","POD changes invalidate the reviewed source");podChanged=false;
changed=true;assert.equal((await request(send)).error.message,"workflow_draft_changed");changed=false;relinked=true;assert.equal((await request(send)).error?.message,"workflow_draft_changed","A changed reservation link is stale even when every displayed source fact matches");relinked=false;denied=true;assert.equal((await request(send)).error.message,"visit_record_denied");denied=false;
const preparedAgain=(await prepare("visit-handoff",revisions["visit-handoff"],values,selection)).result;send=sendInput(preparedAgain,"visit-handoff",revisions["visit-handoff"],values,selection);const delivered=(await request(send)).result;assert.equal(delivered.status,"sent");assert.equal(writes.length,1);assert.equal(writes[0].dto.plainText,preparedAgain.text);changed=true;denied=true;const beforeReplayReads=reads.length;assert.deepEqual((await request(send)).result,delivered);assert.equal(reads.length,beforeReplayReads);assert.equal(writes.length,1);assert.equal((await request({...send,values:{...values,area:"Changed field"}})).error.message,"workflow_draft_changed");denied=false;changed=false;
const wrongRoot=await capability("other-root");assert.equal((await call(envelope("commands.ai.workflow",{targetCapability:wrongRoot,action:"status",operationId:send.operationId,draftToken:send.draftToken}))).error.message,"workflow_draft_expired_or_mismatched");
const newBundle={...bundles["visit-handoff"],resources:[{...bundles["visit-handoff"].resources[0],content:JSON.stringify({...definitions["visit-handoff"],title:"New title",template:"New template {{person}} {{area}} {{revision}} {{exceptions}}"})}]};assert.equal((await admin("skill.publish",newBundle)).status,200);assert.equal((await prepare("visit-handoff",revisions["visit-handoff"],values,selection)).error.message,"workflow_skill_unavailable");await admin("skill.toggle",{name:"visit-handoff",enabled:true});const pinned=(await prepare("visit-handoff",revisions["visit-handoff"],values,selection)).result;assert.equal(pinned.text,preparedAgain.text,"Opened revision remains pinned after a new publication");await admin("skill.toggle",{name:"visit-handoff",enabled:false});assert.equal((await request(sendInput(pinned,"visit-handoff",revisions["visit-handoff"],values,selection))).error.message,"workflow_skill_unavailable");assert.deepEqual((await request({action:"status",operationId:send.operationId,draftToken:send.draftToken})).result,delivered);
const manualValues={audience:"운영팀",notice:"Synthetic notice",when:"Tomorrow"},beforeManual=reads.length;const manualPrefill=(await request({action:"prefill",name:"staff-notice",revision:revisions["staff-notice"]})).result;assert.equal(manualPrefill.values.audience,"");const manualDraft=(await prepare("staff-notice",revisions["staff-notice"],manualValues)).result;const manualSend=sendInput(manualDraft,"staff-notice",revisions["staff-notice"],manualValues);writeMode="unknown";const uncertain=(await request(manualSend)).result;assert.equal(uncertain.status,"uncertain");assert.equal(writes.length,2);assert.deepEqual((await request(manualSend)).result,uncertain);assert.equal(reads.length,beforeManual,"Manual workflows never read the visit database");assert.equal(writes.length,2);
await mf.dispose();mf=new Miniflare(options());assert.deepEqual((await request(send)).result,delivered);assert.deepEqual((await request(manualSend)).result,uncertain);assert.equal(writes.length,2,"Cold restart never resends completed or uncertain work");
const serverErrorDraft=(await prepare("staff-notice",revisions["staff-notice"],manualValues)).result,serverErrorInput=sendInput(serverErrorDraft,"staff-notice",revisions["staff-notice"],manualValues);writeMode="server-error";const serverErrorReceipt=(await request(serverErrorInput)).result;assert.equal(serverErrorReceipt.status,"uncertain","HTTP500 may follow provider-side delivery and must not be treated as a safe rejection");assert.equal(writes.length,3);assert.deepEqual((await request(serverErrorInput)).result,serverErrorReceipt);assert.equal(writes.length,3);
const stagedDraft=(await prepare("staff-notice",revisions["staff-notice"],manualValues)).result,stagedPayload=JSON.parse(Buffer.from(stagedDraft.draftToken.split(".")[0],"base64url")),stagedActor=await assistant();await stagedActor.fetch("https://internal.invalid/fixture/stage",{method:"POST",body:JSON.stringify({operationId:stagedDraft.operationId,requestDigest:hash(JSON.stringify(stagedPayload))})});await mf.dispose();mf=new Miniflare(options());const stagedReceipt=(await request(sendInput(stagedDraft,"staff-notice",revisions["staff-notice"],manualValues))).result;assert.equal(stagedReceipt.status,"uncertain");assert.equal(writes.length,3,"A restarted sending claim is uncertain and never resent");
const actor=await assistant(),inspect=await (await actor.fetch("https://internal.invalid/fixture/inspect")).json();assert.equal(inspect.modelCalls,0);assert.equal(inspect.commandRows,0);assert.equal(inspect.channelRows,0);assert.deepEqual(inspect.runtime,[]);assert.ok(!JSON.stringify(inspect.rows).includes("Synthetic")&&!JSON.stringify(inspect.rows).includes(patientId));for(const row of inspect.rows)assert.deepEqual(Object.keys(row).sort(),row.replyId?["key","replyId","requestDigest","state"]:["key","requestDigest","state"]);
const internalTarget={channelId:channel,groupId:group,rootMessageId:root,managerId:manager};const conflict=await (await actor.fetch("https://internal.invalid/fixture/status",{method:"POST",body:JSON.stringify({target:internalTarget,operationId:send.operationId,requestDigest:"00".repeat(32)})})).json();assert.equal(conflict.error,"workflow_operation_conflict");const spoof=await (await actor.fetch("https://internal.invalid/fixture/status",{method:"POST",body:JSON.stringify({target:{...internalTarget,tenantId:"other"},operationId:send.operationId,requestDigest:"00".repeat(32)})})).json();assert.equal(spoof.error,"visit_target_invalid");const wrongActor=await (await actor.fetch("https://internal.invalid/fixture/status",{method:"POST",body:JSON.stringify({target:{...internalTarget,rootMessageId:"another-root"},operationId:send.operationId,requestDigest:"00".repeat(32)})})).json();assert.equal(wrongActor.error,"workflow_actor_mismatch");
const db=await mf.getD1Database("CONVERSATIONS","cloud"),tables=await db.prepare("SELECT name FROM sqlite_master WHERE name LIKE 'ca_%'").all();for(const name of ["ca_asks","ca_entries","ca_channel_messages","ca_command_receipts"])if(tables.results.some(row=>row.name===name))assert.equal((await db.prepare(`SELECT COUNT(*) AS n FROM ${name}`).first()).n,0,"Workflow content never enters generic D1 conversation records");
await mf.dispose();mf=new Miniflare(options("another-fixture-tenant"));assert.ok((await request({action:"catalog"})).error,"Existing owner and Assistant reject a deployment tenant change");assert.equal(writes.length,3);
const invalid={...bundles["staff-notice"],resources:[{...bundles["staff-notice"].resources[0],content:'{"schemaVersion":999}'}]};await mf.dispose();mf=new Miniflare(options());assert.equal((await admin("skill.publish",invalid)).error,"workflow_definition_invalid");
console.log("Workflow checks passed: two reusable customer forms, selected linked reservation projection, digest-only operation-bound draft, reauthorization/source refresh, revision pin and disable, manual no-DB, exact-root native send, replay/conflict/cold restart/uncertain, tenant spoof guards, and no model or clinical transcript effects.");
}finally{await mf.dispose();await rm(persistence,{recursive:true,force:true});}
