export function aiPanel() {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI 스레드 도우미</title><style>
  body{margin:0;padding:20px;font:14px system-ui;color:#17212b;background:#f7f8fa}h1{font-size:20px;margin:0 0 8px}p{line-height:1.6}button,select,textarea{font:inherit;border:1px solid #cdd3dc;border-radius:8px;padding:10px;background:white}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}.row{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}textarea{width:100%;box-sizing:border-box;min-height:88px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:white;border-radius:10px;padding:14px;line-height:1.6}label{display:block;margin-top:12px}.error{color:#a42121}</style></head><body>
  <h1>AI 스레드 도우미</h1><p id="context">채널톡 연결을 확인하고 있습니다.</p><div class="row"><button data-action="help" disabled>도움말</button><button data-action="history" disabled>전체 대화 이력</button><button id="close" disabled>닫기</button></div>
  <label for="question">이 스레드에 대해 질문하세요</label><textarea id="question" placeholder="예: 지금까지 나온 내용을 정리해 줘" disabled></textarea><label><input id="share-context" type="checkbox" disabled> 조회 API 없이, 직접 공유한 내용만 사용하기</label><label for="shared-context">직접 공유할 내용 (선택)</label><textarea id="shared-context" placeholder="비공개 팀챗에서 복사한 내용 등, AI에 직접 공유하려는 내용을 붙여넣으세요." disabled></textarea><p>직접 공유를 선택하면 API 조회를 하지 않습니다. 전체 이력을 가져왔다고 표시하지 않습니다.</p><div class="row"><button data-action="ask" disabled>질문하기</button><button id="retry" hidden>같은 요청 확인</button></div>
  <label for="model">모델</label><div class="row"><select id="model" disabled></select><button data-action="model" disabled>모델 적용</button></div>
  <label for="thinking">생각 수준</label><div class="row"><select id="thinking" disabled></select><button data-action="thinking" disabled>생각 수준 적용</button></div><p id="state" role="status"></p><pre id="answer" aria-live="polite"></pre>
  <script>
  const $=id=>document.getElementById(id), bridge=window.ChannelIOWam;let pending=null,appId,targetCapability,rootAvailable=false,busy=false;
  const errorLabels={source_history_api_denied:'채널톡 조회 API가 이 대화 접근을 거절했습니다. 비공개 팀챗은 현재 API 키로 읽을 수 없습니다.',source_history_membership_denied:'이 비공개 팀챗의 참여자로 확인되지 않았습니다.',source_history_not_configured:'관리자가 채널톡 조회 API를 연결해야 합니다.',command_thread_required:'스레드 댓글 입력창에서 /ai를 실행해 주세요.',command_operation_conflict:'같은 요청 번호의 내용이 달라졌습니다. 기존 요청을 먼저 확인해 주세요.',command_capability_expired_or_mismatched:'화면 연결이 만료되었습니다. 닫고 /ai를 다시 실행해 주세요.'};
  function enable(){document.querySelectorAll('[data-action]').forEach(button=>button.disabled=busy||!rootAvailable&&button.dataset.action!=='help');['question','model','thinking','share-context'].forEach(id=>$(id).disabled=busy||!rootAvailable);$('shared-context').disabled=busy||!rootAvailable||!$('share-context').checked;$('close').disabled=false;}
  function show(result){$('state').className=result.status==='failed'||result.status==='uncertain'?'error':'';$('state').textContent=result.status==='pending'?'요청을 처리하고 있습니다.':result.status==='uncertain'?'결과 확인이 필요합니다. 같은 변경을 반복하지 않습니다.':result.status==='failed'?'요청을 완료하지 못했습니다.':'완료';
    if(result.error)$('answer').textContent=errorLabels[result.error]||('요청 오류: '+result.error);else if(result.history)$('answer').textContent=(result.history.complete?'전체 이력을 조회했습니다.':'이력 일부를 조회했습니다 ('+result.history.incompleteReason+'). 다음 조회가 필요합니다.')+'\\n\\n'+result.history.messages.map(message=>message.name+' · '+message.createdAt+'\\n'+message.text).join('\\n\\n');else $('answer').textContent=(result.contextSource==='shared'?'직접 공유한 내용으로 답변했습니다. 전체 이력 조회 결과가 아닙니다.\\n\\n':'')+(result.message||'');
    if(result.settings){for(const [id,choices,selected] of [['model',result.settings.models,result.settings.model.id],['thinking',result.settings.thinkingChoices,result.settings.thinking.value]]){const select=$(id);select.replaceChildren();choices.forEach(choice=>{const option=document.createElement('option');option.value=choice.id||choice.value;option.textContent=choice.label;option.selected=option.value===selected;select.append(option);});}}
  }
  async function call(name){const envelope=await bridge.callFunction({appId,name,params:pending});if(envelope.error)throw new Error(envelope.error.message||'command_failed');return envelope.result??envelope;}
  async function run(action,args){if(busy)return;if(!pending)pending={targetCapability,operationId:crypto.randomUUID(),action,args,...(action==='ask'?{contextSource:$('share-context').checked?'shared':'api',sharedContext:$('share-context').checked?$('shared-context').value:''}:{})};busy=true;enable();$('retry').hidden=true;try{let result=await call('commands.ai.execute');show(result);for(let i=0;result.status==='pending'&&i<90;i++){await new Promise(resolve=>setTimeout(resolve,1000));result=await call('commands.ai.status');show(result);}if(result.status==='pending')throw new Error('request_still_pending');pending=null;}catch(error){$('state').className='error';$('state').textContent=errorLabels[error.message]||'응답을 확인하지 못했습니다. 같은 요청 확인을 눌러 주세요.';$('retry').hidden=false;}finally{busy=false;enable();}}
  document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{if(pending){$('state').textContent='먼저 같은 요청 확인을 눌러 이전 결과를 확인해 주세요.';return;}const action=button.dataset.action;run(action,action==='ask'?$('question').value.trim():action==='model'?$('model').value:action==='thinking'?$('thinking').value:'');}));
  $('retry').addEventListener('click',()=>pending&&run(pending.action,pending.args));$('close').addEventListener('click',()=>bridge.close());$('share-context').addEventListener('change',enable);
  try{if(!bridge)throw Error('bridge_missing');appId=bridge.getWamData('appId');targetCapability=bridge.getWamData('targetCapability');rootAvailable=bridge.getWamData('rootAvailable')===true;if(typeof appId!=='string'||typeof targetCapability!=='string')throw Error('context_missing');bridge.setSize({height:620});$('context').textContent=rootAvailable?'서버에서 스레드 원글을 받았습니다. '+(bridge.getWamData('rootMessageId')?'채널톡 화면에도 원글 정보가 있습니다.':'화면의 원글 정보는 별도로 제공되지 않았습니다.')+' 질문과 설정은 현재 스레드에만 적용됩니다.':'스레드 댓글 입력창에서 /ai를 실행하면 질문과 이력을 사용할 수 있습니다.';enable();run('help','');}catch{$('context').textContent='채널톡에서 /ai 명령으로 이 화면을 열어 주세요.';}
  </script></body></html>`;
}
