import { startMarkup, startScript } from "./start-view.js";
import { workflowMarkup, workflowScript } from "./workflow-view.js";
import { visitScript } from "./visit-view.js";

export function aiPanel() {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI 스레드 도우미</title><style>
  body{margin:0;padding:20px;font:14px system-ui;color:#17212b;background:#f7f8fa}h1{font-size:20px;margin:0 0 8px}p{line-height:1.6}button,select,textarea,input{font:inherit;border:1px solid #cdd3dc;border-radius:8px;padding:10px;background:white}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}.row{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}textarea{width:100%;box-sizing:border-box;min-height:88px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:white;border-radius:10px;padding:14px;line-height:1.6}label{display:block;margin-top:12px}.error{color:#a42121}.visit-panel{padding:16px;border:1px solid #cdd3dc;border-radius:12px;margin:20px 0}.visit-panel h2{margin:0;font-size:18px}.visit-panel input,.visit-panel select{max-width:100%;box-sizing:border-box}.visit-panel fieldset{border:1px solid #cdd3dc;border-radius:8px;margin-top:16px}.visit-panel #visit-mode{font-weight:600}body.starting{padding:16px}body.starting h1{font-size:18px}body.starting label{margin-top:8px}body.starting .row{margin:8px 0}body.starting .visit-panel{margin:8px 0;padding:12px}body.starting .visit-panel h2{font-size:16px}body.starting .visit-panel>p:first-of-type,body.starting #start-panel h2{display:none}pre:empty{display:none}</style></head><body>
  <h1>AI 스레드 도우미</h1><p id="context">채널톡 연결을 확인하고 있습니다.</p><div class="row"><button data-action="help" disabled>도움말</button><button data-action="history" disabled>전체 대화 이력</button><button id="close" disabled>닫기</button></div>
  ${workflowMarkup}
  <label for="model">모델</label><div class="row"><select id="model" disabled></select><button data-action="model" disabled>모델 적용</button></div>
  <label for="thinking">생각 수준</label><div class="row"><select id="thinking" disabled></select><button data-action="thinking" disabled>생각 수준 적용</button></div>
  ${startMarkup}
  <section id="thread-content"><label for="question">이 스레드에 대해 질문하세요</label><textarea id="question" placeholder="예: 지금까지 나온 내용을 정리해 줘" disabled></textarea><label><input id="share-context" type="checkbox" disabled> 조회 API 없이, 직접 공유한 내용만 사용하기</label><label for="shared-context">직접 공유할 내용 (선택)</label><textarea id="shared-context" placeholder="비공개 팀챗에서 복사한 내용 등, AI에 직접 공유하려는 내용을 붙여넣으세요." disabled></textarea><p>직접 공유를 선택하면 API 조회를 하지 않습니다. 전체 이력을 가져왔다고 표시하지 않습니다.</p><div class="row"><button data-action="ask" disabled>질문하기</button><button data-action="image" disabled>이미지 만들기</button><button id="retry" hidden>같은 요청 확인</button></div>
  <p>이미지 만들기는 입력한 설명으로 이미지를 만들고, 관리자가 첨부를 활성화한 방에서는 현재 스레드에 보냅니다.</p>
  <div class="row"><button data-action="ask" data-prompt="이 스레드의 핵심 내용과 결정 사항을 간결하게 요약해 주세요. 확인되지 않은 내용은 추측하지 마세요." disabled>대화 요약</button><button data-action="ask" data-prompt="이 스레드에서 나온 할 일을 담당자와 기한으로 정리해 주세요. 담당자나 기한이 명시되지 않았다면 미정으로 표시하고, 없는 할 일은 만들지 마세요." disabled>할 일 정리</button><button data-action="ask" data-prompt="이 스레드에 답할 메시지 초안을 작성해 주세요. 확인되지 않은 사실이나 약속은 만들지 말고, 초안만 이 화면에 표시하세요. 실제 메시지는 보내지 마세요." disabled>답변 초안</button></div></section>
<p id="state" role="status"></p><pre id="answer" aria-live="polite"></pre><div id="image-result" hidden></div>
  <script>
  const $=id=>document.getElementById(id), bridge=window.ChannelIOWam;let pending=null,appId,targetCapability,rootAvailable=false,busy=false;
  const errorLabels={source_history_api_denied:'채널톡 조회 API가 이 대화 접근을 거절했습니다. 비공개 팀챗은 현재 API 키로 읽을 수 없습니다.',source_history_membership_denied:'이 비공개 팀챗의 참여자로 확인되지 않았습니다.',source_history_not_configured:'관리자가 채널톡 조회 API를 연결해야 합니다.',command_thread_required:'스레드 댓글 입력창에서 /ai를 실행해 주세요.',command_operation_conflict:'같은 요청 번호의 내용이 달라졌습니다. 기존 요청을 먼저 확인해 주세요.',command_image_target_denied:'이미지 생성은 관리자가 지정한 테스트방에서 사용할 수 있습니다.',command_capability_expired_or_mismatched:'화면 연결이 만료되었습니다. 닫고 /ai를 다시 실행해 주세요.'};
  const inputErrors={command_question_required:'질문을 입력해 주세요.',command_argument_invalid:'입력 내용을 확인하고 다시 선택해 주세요.',command_operation_invalid:'요청 내용을 확인하고 다시 실행해 주세요.',command_context_invalid:'직접 공유할 내용과 선택을 확인해 주세요.'};
  function enable(){document.body.classList.toggle('starting',!rootAvailable);$('thread-content').hidden=!rootAvailable;$('workflow-details').hidden=!rootAvailable;document.querySelector('[data-action="history"]').hidden=!rootAvailable;document.querySelectorAll('[data-action]').forEach(button=>button.disabled=busy||!rootAvailable&&button.dataset.action!=='help');['question','share-context'].forEach(id=>$(id).disabled=busy||startBusy||!rootAvailable);['model','thinking'].forEach(id=>$(id).disabled=busy||startBusy||!!startPending||!rootAvailable&&!startReady);$('shared-context').disabled=busy||!rootAvailable||!$('share-context').checked;$('close').disabled=false;visitEnable();startEnable();}
  function show(result){$('state').className=result.status==='failed'||result.status==='uncertain'?'error':'';$('state').textContent=result.status==='pending'?'요청을 처리하고 있습니다.':result.status==='uncertain'?'결과 확인이 필요합니다. 같은 변경을 반복하지 않습니다.':result.status==='failed'?'요청을 완료하지 못했습니다.':'완료';
    if(result.error)$('answer').textContent=errorLabels[result.error]||('요청 오류: '+result.error);else if(result.history)$('answer').textContent=(result.history.complete?'전체 이력을 조회했습니다.':'이력 일부를 조회했습니다 ('+result.history.incompleteReason+'). 다음 조회가 필요합니다.')+'\\n\\n'+result.history.messages.map(message=>message.name+' · '+message.createdAt+'\\n'+message.text).join('\\n\\n');else $('answer').textContent=(result.contextSource==='shared'?'직접 공유한 내용으로 답변했습니다. 전체 이력 조회 결과가 아닙니다.\\n\\n':'')+(result.message||'');
    const card=$('image-result');card.replaceChildren();card.hidden=!result.image;
    if(result.image){const image=result.image;const line=document.createElement('p');line.textContent=image.status==='ready'?'이미지 저장 완료 · '+image.width+' × '+image.height+' · '+image.mediaType:'이미지 생성 오류: '+(image.code||'image_generation_unknown');card.append(line);
      if(image.status==='ready'){try{const url=new URL(image.url);if(url.protocol==='https:'&&!url.username&&!url.password&&!url.search&&!url.hash&&/^\\/assets\\/[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(url.pathname)){const link=document.createElement('a');link.href=url.href;link.textContent='저장된 이미지 보기 (관리자 로그인)';link.target='_blank';link.rel='noopener noreferrer';card.append(link);}}catch{}}
      if(result.delivery){const line=document.createElement('p');line.textContent=result.delivery.status==='sent'?'채널톡 스레드에 이미지 첨부 완료':result.delivery.status==='disabled'?'이 방에서는 이미지 첨부가 꺼져 있습니다.':'이미지는 저장됐지만 첨부 결과를 확인해야 합니다. 자동으로 다시 보내지 않습니다.';card.append(line);}
      if(image.diagnostic){const d=image.diagnostic;const info=document.createElement('p');info.textContent='요청 진단 · HTTP '+(Number.isInteger(d.status)?d.status:'확인 불가')+' · '+({upstream_blocked:'서비스 접근 차단',auth_required:'로그인 필요',permission_denied:'사용 권한 없음',rate_limited:'사용량 제한',upstream_error:'서비스 오류'}[d.category]||'확인 필요')+(d.challenge===true?' · 접근 확인 요청':'');card.append(info);}}
    if(result.settings){for(const [id,choices,selected] of [['model',result.settings.models,result.settings.model.id],['thinking',result.settings.thinkingChoices,result.settings.thinking.value]]){const select=$(id);select.replaceChildren();choices.forEach(choice=>{const option=document.createElement('option');option.value=choice.id||choice.value;option.textContent=choice.label;option.selected=option.value===selected;select.append(option);});}}
  }
  async function call(name){const envelope=await bridge.callFunction({appId,name,params:pending});if(envelope.error)throw new Error(envelope.error.message||'command_failed');return envelope.result??envelope;}
  async function run(action,args){if(busy)return;if(!pending&&['ask','image'].includes(action)&&!args.trim()){$('state').className='error';$('state').textContent=inputErrors.command_question_required;$('retry').hidden=true;$('question').focus();return;}if(!pending)pending={targetCapability,operationId:crypto.randomUUID(),action,args,...(action==='ask'?{contextSource:$('share-context').checked?'shared':'api',sharedContext:$('share-context').checked?$('shared-context').value:''}:{})};busy=true;enable();$('retry').hidden=true;$('state').className='';$('state').textContent='요청을 처리하고 있습니다.';try{let result=await call('commands.ai.execute');show(result);for(let i=0;result.status==='pending'&&i<90;i++){await new Promise(resolve=>setTimeout(resolve,1000));result=await call('commands.ai.status');show(result);}if(result.status==='pending')throw new Error('request_still_pending');pending=null;}catch(error){const rejected=Object.hasOwn(inputErrors,error.message);if(rejected)pending=null;$('state').className='error';$('state').textContent=rejected?inputErrors[error.message]:errorLabels[error.message]||'응답을 확인하지 못했습니다. 같은 요청 확인을 눌러 주세요.';$('retry').hidden=rejected;}finally{busy=false;enable();}}
  document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{if(pending){$('state').textContent='먼저 같은 요청 확인을 눌러 이전 결과를 확인해 주세요.';return;}const action=button.dataset.action;run(action,['ask','image'].includes(action)?(button.dataset.prompt||$('question').value.trim()):action==='model'?$('model').value:action==='thinking'?$('thinking').value:'');}));
  $('retry').addEventListener('click',()=>pending&&run(pending.action,pending.args));$('close').addEventListener('click',()=>bridge.close());$('share-context').addEventListener('change',enable);
  ${visitScript}
  ${workflowScript}
  ${startScript}
  async function initialize(){try{if(!bridge)throw Error('bridge_missing');appId=bridge.getWamData('appId');targetCapability=bridge.getWamData('targetCapability');rootAvailable=bridge.getWamData('rootAvailable')===true;if(typeof appId!=='string'||typeof targetCapability!=='string')throw Error('context_missing');bridge.setSize({height:620});let source='명령 요청에서 스레드 원글을 받았습니다.';const hostRoot=bridge.getWamData('rootMessageId');if(!rootAvailable&&typeof hostRoot==='string'&&/^[A-Za-z0-9_:-]{1,255}$/.test(hostRoot)){const envelope=await bridge.callFunction({appId,name:'commands.ai.bindThread',params:{targetCapability,rootMessageId:hostRoot}});if(envelope.error)throw Error(envelope.error.message||'command_bind_failed');const result=envelope.result??envelope;if(typeof result.targetCapability!=='string'||result.rootAvailable!==true)throw Error('context_missing');targetCapability=result.targetCapability;rootAvailable=true;source='채널톡 화면에서 선택한 원글을 사용합니다.';}$('context').textContent=rootAvailable?source+' 질문과 설정은 현재 스레드에만 적용됩니다.':'업무와 AI 설정을 고른 뒤 새 업무를 시작할 수 있습니다.';enable();if(rootAvailable){workflowLoad();run('help','');}else startLoad();}catch(error){$('context').textContent=errorLabels[error.message]||'채널톡에서 /ai 명령으로 이 화면을 열어 주세요.';}}
  initialize();
  </script></body></html>`;
}
