export const startMarkup = `<section id="start-panel" class="visit-panel" hidden><h2>새 업무 시작</h2><p>업무·모델·생각 수준을 먼저 고르세요. 저장된 직원 기본값을 불러오며, 시작에 성공하면 이번 선택을 다음 새 스레드에도 적용합니다. 버튼을 누르면 이 방에 새 원글을 하나 만들고, 그 스레드에서 양식과 질문을 이어갑니다.</p><button id="start-thread" disabled>새 업무 시작</button><button id="start-status" hidden>시작한 요청 결과 확인</button><p id="start-state" role="status"></p></section>`;
export const startScript = `
  let startReady=false,startBusy=false,startPending=null,startEpoch=0;
  const startLabels={command_start_not_configured:'관리자가 새 업무 시작 연결을 설정해야 합니다.',command_start_group_uncertain:'이 방에서 시작한 요청의 결과를 관리자가 확인해야 합니다.',command_start_launch_used:'이 화면에서 이미 시작한 요청입니다. 결과 확인을 눌러 주세요.',command_start_delivery_denied:'관리자가 지정한 방에서만 새 업무를 시작할 수 있습니다.',workflow_skill_unavailable:'선택한 업무가 변경됐습니다. 목록을 새로고침하세요.',model_not_permitted:'선택한 모델을 사용할 수 없습니다. 목록을 새로고침하세요.'};
  function startEnable(){$('start-panel').hidden=rootAvailable;$('start-thread').hidden=!!workflowCurrent&&workflowCurrent.definition.source!=='visit-context';$('start-thread').disabled=rootAvailable||!startReady||startBusy||!!startPending||busy||workflowBusy;$('start-status').hidden=!startPending||rootAvailable;$('start-status').disabled=startBusy;if(!rootAvailable&&startReady&&!startBusy&&!startPending&&!workflowBusy&&$('start-state').className!=='error')$('start-state').textContent=workflowCurrent?.definition.source==='visit-context'?'새 업무 시작을 누른 뒤 환자와 방문을 선택하세요. 조회한 내용을 직접 수정할 수 있습니다.':workflowCurrent?'준비할 내용을 적고 새 스레드에서 초안 만들기를 누르세요. 저장된 AI 설정을 사용합니다.':'업무 없이 시작하려면 새 업무 시작을 누르세요. 저장된 AI 설정을 사용합니다.';for(const action of ['model','thinking'])document.querySelector('[data-action="'+action+'"]').hidden=!rootAvailable;}
  async function startCall(params){const envelope=await bridge.callFunction({appId,name:'commands.ai.start',params});if(envelope.error)throw Error(envelope.error.message||'command_start_failed');return envelope.result??envelope;}
  async function startLoad(chosen){if(rootAvailable||startPending||startBusy)return;const epoch=++startEpoch;startReady=false;workflowCurrent=null;visitInvalidate(true);$('visit-picker').hidden=true;$('workflow-fields').replaceChildren();$('workflow-checks').replaceChildren();workflowBusy=true;enable();$('start-state').textContent='선택할 업무와 설정을 불러오고 있습니다.';try{const result=await startCall({targetCapability,action:'options'});if(epoch!==startEpoch||rootAvailable||startPending)return;if(result.kind!=='start-options'||!Array.isArray(result.workflows)||!result.settings)throw Error('command_start_failed');workflowCatalog=result.workflows;visitOptions('workflow-select',workflowCatalog,'업무 없이 AI 대화 시작',row=>row.definition.title);$('workflow-select').querySelectorAll('option').forEach((option,index)=>{if(index)option.value=workflowCatalog[index-1].name;});show({status:'done',settings:result.settings});startReady=true;if(chosen){const row=workflowCatalog.find(row=>row.name===chosen.name&&row.revision===chosen.revision);if(row){$('workflow-select').value=row.name;await workflowChoose();}else{$('workflow-state').className='error';$('workflow-state').textContent=workflowLabels.workflow_skill_unavailable;}}$('start-state').className='';}catch(error){if(epoch===startEpoch){$('start-state').className='error';$('start-state').textContent=startLabels[error.message]||errorLabels[error.message]||'선택 목록을 불러오지 못했습니다. 목록 새로고침을 눌러 주세요.';}}finally{if(epoch===startEpoch){workflowBusy=false;enable();}}}
  async function startThread(statusOnly=false){if(startBusy||rootAvailable||!statusOnly&&!startReady)return;if(!startPending){startPending={targetCapability,action:'create',operationId:crypto.randomUUID(),confirmed:true,intent:{modelId:$('model').value,thinkingLevel:$('thinking').value,...(workflowCurrent?{workflow:{name:workflowCurrent.name,revision:workflowCurrent.revision}}:{})}};}const epoch=++startEpoch;startBusy=true;enable();$('start-state').className='';$('start-state').textContent=statusOnly?'시작한 요청 결과를 확인하고 있습니다.':'새 원글을 만들고 있습니다.';try{const result=await startCall(statusOnly?{targetCapability:startPending.targetCapability,action:'status',operationId:startPending.operationId}:startPending);if(epoch!==startEpoch)return;if(result.status==='ready'&&result.rootAvailable===true&&typeof result.targetCapability==='string'){targetCapability=result.targetCapability;rootAvailable=true;const chosen=startPending.intent.workflow;startPending=null;$('context').textContent='새 업무 대화를 시작했습니다. 이 대화에서 준비를 이어가세요.';$('start-state').textContent='새 업무를 시작했습니다.';await workflowLoad(chosen);if(!chosen)$('workflow-state').textContent='필요하면 업무 양식을 선택하세요.';}else{$('start-state').className='error';$('start-state').textContent=result.status==='failed'?'새 원글 생성이 거절됐습니다. 닫고 다시 /ai를 실행하세요.':result.status==='abandoned'?'관리자가 이 시작을 종료했습니다. 닫고 /ai를 다시 실행하세요.':'시작한 요청 결과를 확인해야 합니다. 원글을 자동으로 다시 만들지 않습니다. 결과 확인 후에도 그대로면 관리자에게 요청 번호 '+startPending.operationId+'를 전달하세요.';}}catch(error){if(epoch===startEpoch){$('start-state').className='error';$('start-state').textContent=startLabels[error.message]||errorLabels[error.message]||'시작한 결과를 확인하지 못했습니다. 시작한 요청 결과 확인을 눌러 주세요. 요청 번호 '+startPending.operationId;}}finally{if(epoch===startEpoch){startBusy=false;enable();if(rootAvailable)await workflowResume();}}}
  $('start-thread').addEventListener('click',()=>{workflowLaunch=null;startThread();});$('start-status').addEventListener('click',()=>startThread(true));
`;
