export const visitMarkup = `<section aria-labelledby="visit-heading" class="visit-panel"><h2 id="visit-heading">내원 도우미</h2><p>환자와 방문을 직접 선택한 뒤, 확인한 내용으로 안내 초안을 만드세요.</p><p id="visit-mode" role="status"></p>
  <label for="visit-query">1. 환자 찾기</label><div class="row"><input id="visit-query" maxlength="64" placeholder="이름 또는 식별 참고 번호" disabled><button id="visit-search" disabled>검색</button></div>
  <label for="visit-patient">2. 검색 결과에서 환자 선택</label><select id="visit-patient" disabled><option value="">환자를 선택하세요</option></select>
  <label for="visit-select">3. 방문 선택</label><select id="visit-select" disabled><option value="">방문을 선택하세요</option></select><pre id="visit-context"></pre>
  <fieldset id="visit-fields" disabled><legend>4. 안내에 넣을 내용 확인</legend><label for="visit-concern">상담·치료 부위</label><input id="visit-concern" maxlength="200" placeholder="확인한 내용만 입력하세요">
  <label for="visit-revision">재수술 여부</label><select id="visit-revision"><option value="unknown">확인 필요</option><option value="yes">예</option><option value="no">아니요</option></select>
  <label for="visit-exceptions">일정 예외</label><input id="visit-exceptions" maxlength="500" placeholder="예외가 없으면 ‘없음’이라고 입력하세요">
  <label for="visit-name-check">외부 시스템에서 이름을 확인했나요?</label><select id="visit-name-check"><option value="unknown">확인 필요</option><option value="yes">확인함</option><option value="no">확인하지 않음</option></select></fieldset>
  <div class="row"><button id="visit-arrival" disabled>상담 도착 안내 초안</button><button id="visit-treatment" disabled>치료실 안내 초안</button></div><p id="visit-state" role="status"></p><pre id="visit-draft" aria-live="polite"></pre><p>초안은 이 화면에서 확인하세요. 검색·초안 재시도는 현재 자료를 다시 조회합니다.</p></section>`;

export const visitScript = `
  let visitRevision=0,visitBusy=false,visitContext=null;
  const visitLabels={visit_not_configured:'관리자가 내원 도우미를 연결해야 합니다.',visit_input_invalid:'입력 내용을 확인하고 다시 선택해 주세요.',visit_selection_required:'환자와 방문을 먼저 선택해 주세요.',visit_record_denied:'이 자료를 볼 권한이 없습니다. 관리자에게 접근 권한을 확인해 주세요.',visit_not_found_for_patient:'선택한 환자의 방문을 찾을 수 없습니다. 환자와 방문을 다시 선택해 주세요.',visit_backend_unavailable:'자료를 조회하지 못했습니다. 다시 검색하거나 초안 버튼을 눌러 주세요.',visit_response_invalid:'조회한 자료를 확인하지 못했습니다. 다시 검색해 주세요.',visit_response_too_large:'조회 결과가 너무 많습니다. 검색 내용을 구체적으로 입력해 주세요.'};
  function visitEnable(){const connected=rootAvailable; $('visit-query').disabled=!connected;$('visit-search').disabled=!connected||visitBusy||$('visit-query').value.trim().length<2;$('visit-patient').disabled=!connected||!$('visit-patient').options.length||$('visit-patient').options.length===1;$('visit-select').disabled=!connected||$('visit-select').options.length===1;const selected=connected&&visitContext&&visitContext.patient.id===$('visit-patient').value&&visitContext.selectedVisitId&&visitContext.selectedVisitId===$('visit-select').value;$('visit-fields').disabled=!selected;['visit-arrival','visit-treatment'].forEach(id=>$(id).disabled=!selected||visitBusy);}
  function visitOptions(id,items,placeholder,label){const select=$(id);select.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=placeholder;select.append(first);items.forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=label(item);select.append(option);});}
  function visitClearFields(){$('visit-concern').value='';$('visit-revision').value='unknown';$('visit-exceptions').value='';$('visit-name-check').value='unknown';}
  function visitInvalidate(clearChoices){visitRevision++;visitBusy=false;visitContext=null;$('visit-context').textContent='';$('visit-draft').textContent='';$('visit-state').textContent='';visitClearFields();if(clearChoices){$('visit-mode').textContent='';visitOptions('visit-patient',[],'환자를 선택하세요',item=>item.label);visitOptions('visit-select',[],'방문을 선택하세요',item=>item.date);}visitEnable();}
  async function visitRun(input){if(!rootAvailable)return;const revision=++visitRevision;visitBusy=true;$('visit-draft').textContent='';$('visit-state').className='';$('visit-state').textContent=input.action==='draft'?'초안을 만들고 있습니다.':'자료를 조회하고 있습니다.';visitEnable();try{const envelope=await bridge.callFunction({appId,name:'commands.ai.visit',params:{targetCapability,...input}});if(revision!==visitRevision)return;if(envelope.error)throw Error(envelope.error.message||'visit_backend_unavailable');const result=envelope.result??envelope;if(!['test','live'].includes(result.mode))throw Error('visit_response_invalid');$('visit-mode').textContent=result.mode==='test'?'가상 테스트 자료 · 실제 환자 정보가 아닙니다.':'업무 자료 · 선택한 방문의 조회 결과입니다.';
    if(input.action==='patientSearch'){if(result.kind!=='patients'||!Array.isArray(result.patients))throw Error('visit_response_invalid');visitOptions('visit-patient',result.patients,'환자를 선택하세요',item=>item.label+(item.reference?' · '+item.reference:' · 참고 번호 없음'));$('visit-state').textContent=result.patients.length?'검색 결과에서 환자를 선택하세요. (최대 20명)':'검색 결과가 없습니다. 검색어를 바꿔 주세요.';}
    else if(input.action==='visitSelect'){if(result.kind!=='context'||result.patient?.id!==input.patientId||result.selectedVisitId!==(input.visitId??null))throw Error('visit_response_invalid');visitContext=result;visitOptions('visit-select',result.visits,'방문을 선택하세요',item=>(item.date||'날짜 확인 필요')+' · '+(item.status||'상태 확인 필요')+' · '+item.id.slice(-6));$('visit-select').value=result.selectedVisitId||'';$('visit-context').textContent='선택한 환자: '+result.patient.label+'\\n예약: '+(result.reservations.length?result.reservations.map(row=>(row.at||'날짜 확인 필요')+' · '+(row.type||'유형 확인 필요')+' · '+(row.status||'상태 확인 필요')).join('\\n'):'조회된 예약 없음')+'\\n조회 시각: '+result.observedAt;$('visit-state').textContent=result.selectedVisitId?'확인한 내용을 입력하고 안내 초안을 선택하세요.':result.visits.length?'방문을 직접 선택하세요. (최대 20건)':'조회된 방문이 없습니다. 방문 기록을 확인해 주세요.';}
    else{if(result.kind!=='draft'||!result.draft||!Array.isArray(result.draft.missingFields))throw Error('visit_response_invalid');$('visit-draft').textContent=result.draft.text;$('visit-state').textContent=result.draft.ready?'초안을 확인하세요. 실제 메시지는 보내지 않았습니다.':'확인 필요 또는 미입력 항목이 있습니다. 내용을 확인하고 초안을 다시 만드세요.';}
  }catch(error){if(revision!==visitRevision)return;$('visit-state').className='error';$('visit-state').textContent=visitLabels[error.message]||errorLabels[error.message]||'조회하지 못했습니다. 입력 내용을 확인하고 다시 시도해 주세요.';}finally{if(revision===visitRevision){visitBusy=false;visitEnable();}}}
  $('visit-query').addEventListener('input',()=>visitInvalidate(true));$('visit-search').addEventListener('click',()=>{visitInvalidate(true);visitRun({action:'patientSearch',query:$('visit-query').value.trim()});});
  $('visit-patient').addEventListener('change',()=>{visitInvalidate(false);visitOptions('visit-select',[],'방문을 선택하세요',item=>item.date);const patientId=$('visit-patient').value;if(patientId)visitRun({action:'visitSelect',patientId,visitId:null});});
  $('visit-select').addEventListener('change',()=>{const patientId=$('visit-patient').value,visitId=$('visit-select').value;visitInvalidate(false);if(patientId)visitRun({action:'visitSelect',patientId,visitId:visitId||null});});
  ['visit-concern','visit-revision','visit-exceptions','visit-name-check'].forEach(id=>$(id).addEventListener('input',()=>{visitRevision++;visitBusy=false;$('visit-draft').textContent='';$('visit-state').textContent='';visitEnable();}));
  for(const [id,kind] of [['visit-arrival','arrival'],['visit-treatment','treatment']])$(id).addEventListener('click',()=>visitRun({action:'draft',patientId:$('visit-patient').value,visitId:$('visit-select').value,fields:{kind,concernArea:$('visit-concern').value,revision:$('visit-revision').value,schedulingExceptions:$('visit-exceptions').value,externalNameChecked:$('visit-name-check').value}}));
`;
