export const visitMarkup = `<div id="visit-picker" hidden><p id="visit-mode" class="test-notice" role="status"></p>
  <label for="visit-query">환자 찾기</label><div class="search-row"><input id="visit-query" maxlength="64" placeholder="이름 또는 차트 번호" disabled><button id="visit-search" disabled>검색</button></div>
  <label for="visit-patient">어느 환자인가요?</label><select id="visit-patient" disabled><option value="">환자를 선택하세요</option></select>
  <details id="visit-schedule"><summary>일정 정보 추가 (선택)</summary><label for="visit-select">어느 일정인가요?</label><select id="visit-select" disabled><option value="">일정 없이 작성</option></select><details id="visit-source" hidden><summary id="visit-summary">선택한 환자와 일정</summary><pre id="visit-context"></pre></details></details><p id="visit-state" role="status"></p></div>`;

export const visitScript = `
  let visitRevision=0,visitBusy=false,visitContext=null;
  const visitLabels={visit_not_configured:'관리자가 자료 조회를 연결해야 합니다.',visit_input_invalid:'입력 내용을 확인하고 다시 선택해 주세요.',visit_selection_required:'환자를 선택해 주세요.',visit_record_denied:'이 자료를 볼 권한이 없습니다. 관리자에게 접근 권한을 확인해 주세요.',visit_not_found_for_patient:'선택한 환자의 일정을 찾을 수 없습니다. 환자와 일정을 다시 확인해 주세요.',visit_backend_unavailable:'자료를 조회하지 못했습니다. 다시 검색해 주세요.',visit_response_invalid:'조회한 자료를 확인하지 못했습니다. 다시 검색해 주세요.',visit_response_too_large:'조회 결과가 너무 많습니다. 검색 내용을 구체적으로 입력해 주세요.'};
  const visitTerms={consultation:'상담',surgery:'수술',operation:'수술',procedure:'시술',treatment:'시술',followup:'경과 확인',follow_up:'경과 확인','follow-up':'경과 확인',dressing:'드레싱',arrived:'도착',waiting:'대기',scheduled:'예정',confirmed:'예약 확정',completed:'완료',cancelled:'취소',canceled:'취소',deleted:'삭제',removed:'삭제',no_show:'미내원',noshow:'미내원'};
  function visitTerm(value,fallback=''){const word=String(value||'').trim();return Object.hasOwn(visitTerms,word.toLowerCase())?visitTerms[word.toLowerCase()]:/[가-힣]/.test(word)?word:fallback;}
  function visitDate(value){if(!value)return '날짜 확인 필요';if(/^\\d{4}-\\d{2}-\\d{2}$/.test(value)){const [year,month,day]=value.split('-').map(Number);return year+'년 '+month+'월 '+day+'일';}const date=new Date(value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',hour:'numeric',minute:'2-digit'}).format(date):'날짜 확인 필요';}
  function visitReservation(row,result){return result.reservations.find(item=>item.id===row.reservationId);}
  function visitLabel(row,result){const reservation=visitReservation(row,result);return [visitDate(row.date),visitTerm(reservation?.type,'진료 일정'),reservation?.at?'예약 '+visitDate(reservation.at):'',visitTerm(row.status)].filter(Boolean).join(' · ');}
  function visitEnable(){const connected=(rootAvailable||startReady)&&!workflowPending&&!startPending;$('visit-query').disabled=!connected;$('visit-search').disabled=!connected||visitBusy||$('visit-query').value.trim().length<2;$('visit-patient').disabled=!connected||visitBusy||$('visit-patient').options.length===1;$('visit-select').disabled=!connected||visitBusy||$('visit-select').options.length===1;workflowEnable();}
  function visitOptions(id,items,placeholder,label){const select=$(id);select.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=placeholder;select.append(first);items.forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=label(item);select.append(option);});}
  function visitInvalidate(clearChoices){visitRevision++;visitBusy=false;visitContext=null;$('visit-context').textContent='';$('visit-source').hidden=true;$('visit-source').open=false;$('visit-schedule').open=false;$('visit-summary').textContent='선택한 환자와 일정';$('visit-state').textContent='';workflowReset();if(clearChoices){$('visit-mode').textContent='';visitOptions('visit-patient',[],'환자를 선택하세요',item=>item.label);visitOptions('visit-select',[],'일정 없이 작성',item=>item.date);}visitEnable();}
  async function visitRun(input){if(!rootAvailable&&!startReady||workflowPending||startPending)return;const revision=++visitRevision;let prefilled=false;visitBusy=true;$('visit-state').className='';$('visit-state').textContent='자료를 조회하고 있습니다.';visitEnable();try{const envelope=await bridge.callFunction({appId,name:'commands.ai.visit',params:{targetCapability,...input}});if(revision!==visitRevision)return;if(envelope.error)throw Error(envelope.error.message||'visit_backend_unavailable');const result=envelope.result??envelope;if(!['test','live'].includes(result.mode))throw Error('visit_response_invalid');$('visit-mode').textContent=result.mode==='test'?'가상 테스트 자료':'';
    if(input.action==='patientSearch'){if(result.kind!=='patients'||!Array.isArray(result.patients))throw Error('visit_response_invalid');visitOptions('visit-patient',result.patients,'환자를 선택하세요',item=>item.label+(item.reference?' · '+item.reference:''));$('visit-state').textContent=result.patients.length?'검색 결과에서 환자를 선택하세요.':'검색 결과가 없습니다. 검색어를 바꿔 주세요.';}
    else{if(result.kind!=='context'||result.patient?.id!==input.patientId||result.selectedVisitId!==(input.visitId??null))throw Error('visit_response_invalid');visitContext=result;visitOptions('visit-select',result.visits,'일정 없이 작성',item=>visitLabel(item,result));const labels=result.visits.map(row=>visitLabel(row,result));for(const option of $('visit-select').options)option.disabled=!!option.value&&labels.filter(label=>label===option.textContent).length>1;$('visit-select').value=result.selectedVisitId||'';const selected=result.visits.find(row=>row.id===result.selectedVisitId);$('visit-source').hidden=!selected;$('visit-summary').textContent=result.patient.label+(selected?' · '+visitLabel(selected,result):'');$('visit-context').textContent='환자: '+result.patient.label+'\\n일정: '+(selected?visitLabel(selected,result):'일정 없이 작성합니다.');$('visit-state').textContent=result.selectedVisitId?'선택한 일정 정보로 내용을 준비했습니다.':'환자를 확인했습니다. 일정 없이 작성할 수 있습니다.';
      prefilled=await workflowPrefill()===true;}
  }catch(error){if(revision!==visitRevision)return;$('visit-state').className='error';$('visit-state').textContent=visitLabels[error.message]||errorLabels[error.message]||'조회하지 못했습니다. 입력 내용을 확인하고 다시 시도해 주세요.';}finally{if(revision===visitRevision){visitBusy=false;visitEnable();if(prefilled)await workflowResume();}}}
  $('visit-query').addEventListener('input',()=>visitInvalidate(true));$('visit-query').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.isComposing&&!$('visit-search').disabled){event.preventDefault();$('visit-search').click();}});$('visit-search').addEventListener('click',()=>{visitInvalidate(true);visitRun({action:'patientSearch',query:$('visit-query').value.trim()});});
  $('visit-patient').addEventListener('change',()=>{visitInvalidate(false);visitOptions('visit-select',[],'일정 없이 작성',item=>item.date);const patientId=$('visit-patient').value;if(patientId)visitRun({action:'visitSelect',patientId,visitId:null});});
  $('visit-select').addEventListener('change',()=>{const patientId=$('visit-patient').value,visitId=$('visit-select').value;visitInvalidate(false);if(patientId)visitRun({action:'visitSelect',patientId,visitId:visitId||null});});
`;
